### ISSUE TITLE
Security advisory for 'decompress'

### ISSUE THREAD

**Issue by efh365** [amazon-connect/voicemail-for-amazon-connect#1]
The 'decompress' npm package is vulnerable to Arbitrary File Write according to https://www.npmjs.com/advisories/1217. Decompress is used by Serverless, which is a third party package that is used to build the Lambda functions in this solution. We will track the Serverless issue for a fix and implement when one is available.
https://github.com/serverless/serverless/issues/7402

**Comment by ranman** [comment]
This is resolved with package.json updates in https://github.com/amazon-connect/voicemail-for-amazon-connect/commit/8002ec525cc419a7be8e2b9865e398946a50c588
