### ISSUE TITLE
Unable to create more than one stack

### ISSUE THREAD

**Issue by abilash44** [amazon-connect/voicemail-for-amazon-connect#100]
Hi
I am getting this error when I create more than one stack for the VM solution.  Please let me know how I can create more than one stack in the same AWS account.

![image](https://user-images.githubusercontent.com/7634986/234753211-b8414bfa-7951-4c7d-8531-076cea2e124b.png)

**Comment by gierig1977** [comment]
The error Show up that ACL on S3 buckets not allowed by default. There was a change by Amazon on default handling.
See https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/

That active since 25.04.23

I would also need a solution / fix for the template as I can’t see the solution on that „complex“ setup for my own

**Comment by AgustinaLoyolaM** [comment]
I have exactly the same error, just before going into production with a client. It would be very helpful if someone can provide a solution.  I was able to get to the step of creating "SolutionHelperFunction" but in each step it gives a different error.

**Comment by karl-mentzer** [comment]
Add the following configuration to any S3::Bucket that is specifying the `AccessControl` property:

### YAML
```
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
```

### JSON
```
    "OwnershipControls": {
        "Rules": [
            {
                "ObjectOwnership": "BucketOwnerPreferred"
            }
        ]
    },

**Comment by abilash44** [comment]
That works for the first stack but breaks for the nested stacks.

![image](https://user-images.githubusercontent.com/7634986/235635125-163ba35f-fb38-4844-a038-48c8337389ab.png)

**Comment by abilash44** [comment]
Here are the updated template files that would allow to install VM more than once in a single AWS instance for multiple Amazon Connect. 

The changes are as follows 

voicemail-for-amazon-connect.template 

Goto line 134 and add the S3 bucket.  As mentioned in the README.md file.   The older template file from the pdf won't work for the changes done with S3.


aws-connect-vm.template
Two changes are done to the export 

line - 3671 

"Export": {
        "Name": { "Fn::Sub": "${AWS::StackName}-sls-aws-connect-vm-prod-ServiceEndpoint" }
      }

line - 3697 
"Export": {
        "Name": { "Fn::Sub": "${AWS::StackName}-sls-aws-connect-vm-prod-ServerlessDeploymentBucketName" }
      }

A big shoutout to the AWS support team who made this happen. Can these changes be incorporated to the stack so everyone can use it properly please.
 
[fixed stack with multiple vm creation .zip](https://github.com/amazon-connect/voicemail-for-amazon-connect/files/11460508/fixed.stack.with.multiple.vm.creation.zip)
