### ISSUE TITLE
VM-VoicemailStack-WB-TranscriptionEventsLambda Env. Variable SIGNED_RECORDING_URL_EXP not working

### ISSUE THREAD

**Issue by jcnovoa** [amazon-connect/voicemail-for-amazon-connect#102]
I updated the VM-VoicemailStack-WB-TranscriptionEventsLambda Env. Variable SIGNED_RECORDING_URL_EXP to be greater than 900 and once the signed URL is generated, it still shows 900
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<X-Amz-Expires>900</X-Amz-Expires>
<Expires>2023-05-27T01:46:13Z</Expires>
<ServerTime>2023-05-27T01:54:17Z</ServerTime>

**Comment by virtualgill** [comment]
You will need to also update the **ContactVoicemailStream** lambda SIGNED_RECORDING_URL_EXP env variable.
