### ISSUE TITLE
Not able to open the guide

### ISSUE THREAD

**Issue by ShaliniKrishnamoorthy123** [amazon-connect/voicemail-for-amazon-connect#103]
Getting somme error, while trying to open implementation guide.

https://github.com/amazon-connect/voicemail-for-amazon-connect/blob/development/voicemail-for-amazon-connect-implementation-guide.pdf

**Comment by virtualgill** [comment]
Hi @ShaliniKrishnamoorthy123, I'm not able to recreate this. Can you give any more details? Are you able to open other pdfs on your computer ok?

**Comment by virtualgill** [comment]
Unable to recreate, closing for now.
