### ISSUE TITLE
Voicemail Signed URL Limit increase

### ISSUE THREAD

**Issue by jabshettys1** [amazon-connect/voicemail-for-amazon-connect#105]
Hi Team,

We have a requirement to increase the encrypted voicemail url expiraiton link limit from 900 seconds to 36000 seconds.

Please help me here to update the expiration limit.

Thanks in advance.

Sachin

**Comment by virtualgill** [comment]
Hi @jabshettys1 

This setting is configured when you deploy the Cloudformation in the parameter "RecordingsUrlExpirationTime".

If you already have it deployed, you will find it used in the [Environment Variables](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html) of the \*_VoicemailStream_\* and  \*_TranscriptionEvents_\* Lambda functions as `SIGNED_RECORDING_URL_EXP`, and it can be updated in each of those.

Thanks,
Gillian
