### ISSUE TITLE
Issue with the nested stack

### ISSUE THREAD

**Issue by anchalmarwah** [amazon-connect/voicemail-for-amazon-connect#107]
Hello AWS Team,

Seems the latest update of this solution on 23rd April, is having issues with S3 Bucket policies as below when the nested stack aws-connect-vm tries deploying:
Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: X3XHHE2JQNFHPC7D; S3 Extended Request ID: SNGBLt6HdmD+Sb9GoEjxtYinoY7lCbPlUuUBU6nbUhnNlYRx89/iZnTzCFjy2owEwrceJKGuknY=; Proxy: null)

This is happening as the "Solutions" bucket under mapping seems to be still having the old aws-connect-template with no bucket enforced settings.

However the new update seems to have that policy updated but that template is not uploaded to solutions bucket and causing issues.

I have uploaded that template locally to my s3, changed the master voicemail stack, to point the URL to my bucket object and works fine.

Thanks,
Anchal

**Comment by jimiz12** [comment]
@anchalmarwah Would you be able to share you solution to this?  Did you edit the aws-connect-vm.template to replace the s3 bucket manually created?

**Comment by vardhanpatel** [comment]
Currently seeing this issue as well, i have tried modifying the template and did the following which seems to bypass the error, 

I removed: AccessControl: "LogDeliveryWrite" and then added the following

        OwnershipControls:
         Rules:
          - ObjectOwnership: BucketOwnerEnforced 

However then i see the following error, 

CopyLambdaArtifactsStack .... was not successfully created: The following resource(s) failed to create: [CopyArtifactsHelperFunction].

Resource handler returned message: "The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400,

**Comment by jimiz12** [comment]
@vardhanpatel I ran into a similar issue.  I ended up editing the template and changing nodejsXX to nodejs18 and re-running.

**Comment by virtualgill** [comment]
If you check at the top of the [README](https://github.com/amazon-connect/voicemail-for-amazon-connect) you'll see a link to updated [instructions](https://aws-contact-center-blog.s3.us-west-2.amazonaws.com/voicemail-s3-default-acl-issue/vmv1s3fix.zip) and templates for this issue. This should resolve both issues in this thread.
