### ISSUE TITLE
Changing the voicemail email date from GMT to EST

### ISSUE THREAD

**Issue by kourosh-samia** [amazon-connect/voicemail-for-amazon-connect#11]
There is noway for me to change the timestamp appears in the voicemail email from GMT to EST. This caused me some unhappy clients.

**Comment by efh365** [comment]
You can change the timestamp by modifying the date object here: https://github.com/amazon-connect/voicemail-for-amazon-connect/blob/master/source/aws-connect-vm-serverless/src/service/notification.service.js#L133

**Comment by maekiteasy** [comment]
This is also an issue for our environment. It would be great if there was an easier way to change the time zone other than changing the code. Maybe there could be an environment variable in the Lambda function that could be easily changed.
