### ISSUE TITLE
Transcribe functionality for Spanish Language

### ISSUE THREAD

**Issue by monikadr** [amazon-connect/voicemail-for-amazon-connect#110]
Hello,

I currently have a AWS Connect application that supports EN-US and ES-419/ES-US , In some cases I can have voicemails that are in Spanish language. 

Currently all the transcripts I am seeing are for English, if there is a Spanish voicemail then the transcripts are empty. So is there a way to add functionality for Spanish transcripts?

Thanks,
Monika

**Comment by monikadr** [comment]
I was able to resolve this

**Comment by AdrianMRV** [comment]
> I was able to resolve this

Good morning, 

I am interested in how you were able to solve it for Spanish.
Best regards.

**Comment by monikadr** [comment]
> > I was able to resolve this
> 
> Good morning,
> 
> I am interested in how you were able to solve it for Spanish. Best regards.

Add a attribute languageCode with Spanish language code 
Same is mentioned in the Appendix C: of the implementation guide.
