### ISSUE TITLE
Problem with stack deployment

### ISSUE THREAD

**Issue by AdrianMRV** [amazon-connect/voicemail-for-amazon-connect#114]
![Voicemail](https://github.com/amazon-connect/voicemail-for-amazon-connect/assets/134686181/047c4fb7-706a-4f80-b23d-35d1de44ad7e)
Hi, I am trying to implement the voicemail solution for amazon connect.

Once launched the stack does not finish correctly, it is not able to create the Cognito UserPoolDomain.

Has anyone experienced this kind of issue?

Thank you very much.
Best regards.

**Comment by RayShonami** [comment]
@AdrianMRV did you pull the latest cloud formation template from this repository?

**Comment by AdrianMRV** [comment]
Yes @RayShonami  the last template inside the Deployment folder.
Version 1.4.4, is the correct template, right?
Regards!

**Comment by RayShonami** [comment]
@AdrianMRV  That's right. I'll attempt to re-deploy it again and see what the problem might be.

The only reason I could think this error would appear is that the user pool has a conflict with another user pool or the permissions to make the necessarily changes related to creating the user pool wasn't available. However, I expect the error would appear differently if those two were the potential issues for your experience.

**Comment by AdrianMRV** [comment]
Hello!
I have fixed the error, a mistake of mine, when covering the template I was putting an existing domain name! 
You can mark this problem as solved.
