### ISSUE TITLE
leaving voicemail without agent extension

### ISSUE THREAD

**Issue by akeefk** [amazon-connect/voicemail-for-amazon-connect#119]
Voicemail solution currently allows the caller to leave voicemail only when they know the extension of the agent. Practically this does not suit as standard solution. Hence adding capability where caller can also continue to leave voicemail despite not knowing agent extension by pressing any other key which can send the voicemail to contact center manager.

**Comment by virtualgill** [comment]
Hi there! We will add this request to the backlog for the next version of this solution. In the interim, since this is an Open Source solution, feel free to extend the existing solution to add this in if it's something you need right away.
