### ISSUE TITLE
JSON Array Error in Voice-KvsProcessRecording Lambda Function

### ISSUE THREAD

**Issue by kchaing** [amazon-connect/voicemail-for-amazon-connect#12]
I deployed the stack twice and keep getting errors in the Voice-KvsProcessRecording lambda function which is causing no recordings to show up in S3. I saw that in another issue raised that this error came up for another user, but I am not sure how it was fixed. In CloudWatch I get the following log results (with PII redacted):

Record Data: 
{
    "AWSAccountId": "XXXXXXXXXXXXXXX",
    "AWSContactTraceRecordFormatVersion": "2017-03-10",
    "Agent": null,
    "AgentConnectionAttempts": 0,
    "Attributes": {
        "agentId": "d88d6c02-3598-4133-a29b-XXXXXXXXXX",
        "agentName": "John Doe",
        "encryptVoicemail": "true",
        "extensionNumber": "331",
        "saveCallRecording": "true",
        "startStreamingAudioStatus": "failure",
        "transcribeVoicemail": "true",
        "transferMessage": "Please wait while we transfer you to John Doe"
    },
    "Channel": "VOICE",
    "ConnectedToSystemTimestamp": "2020-04-23T19:59:48Z",
    "ContactId": "21413a18-af77-4699-b396-XXXXXXXXXXXXX",
    "CustomerEndpoint": {
        "Address": "+1XXXXXXXXXX",
        "Type": "TELEPHONE_NUMBER"
    },
    "DisconnectTimestamp": "2020-04-23T20:00:27Z",
    "InitialContactId": null,
    "InitiationMethod": "INBOUND",
    "InitiationTimestamp": "2020-04-23T19:59:48Z",
    "InstanceARN": "arn:aws:connect:us-east-1:XXXXXXXX:instance/XXXXXXX-XXXXX-XXXX-XXXX-b428ecf42a70",
    "LastUpdateTimestamp": "2020-04-23T20:01:33Z",
    "MediaStreams": [
        {
            "Type": "AUDIO"
        }
    ],
    "NextContactId": null,
    "PreviousContactId": null,
    "Queue": {
        "ARN": "arn:aws:connect:us-east-1:XXXXXXXX:instance/XXXXXXX-XXXXX-XXXX-XXXX-b428ecf42a70/queue/agent/d88d6c02-3598-4133-a29b-XXXXXXXXXX",
        "DequeueTimestamp": "2020-04-23T20:00:27Z",
        "Duration": 24,
        "EnqueueTimestamp": "2020-04-23T20:00:03Z",
        "Name": null
    },
    "Recording": null,
    "Recordings": null,
    "SystemEndpoint": {
        "Address": "+1XXXXXXXXXX",
        "Type": "TELEPHONE_NUMBER"
    },
    "TransferCompletedTimestamp": null,
    "TransferredToEndpoint": null
}

org.json.JSONException: JSONObject["Recordings"] is not a JSONArray.

I was not sure how to look at the Lambda function code to try to debug further since I couldnt view it in the inline editor. Any thoughts or suggestions?

**Comment by kchaing** [comment]
Just a thought, do you need to enable call recording in the contact flow somewhere for this to work properly?

**Comment by efh365** [comment]
Please make sure you have enabled live media streaming and data streaming in your Amazon Connect instance: https://docs.aws.amazon.com/solutions/latest/voicemail-for-amazon-connect/deployment.html#step2

You do not need to enable call recording as call recordings only record the conversation once a customer and an agent are connected. You do have to enable live media streaming and start streaming with KVS though.

**Comment by kchaing** [comment]
Thanks, I missed the step for enabling Live Media Streaming when following the guide and that fixed the issue!

**Comment by tydonk** [comment]
I see the same error in my logs for this lambda, "org.json.JSONException: JSONObject["Recordings"] is not a JSONArray".  Voicemails are being delivered intermittently.  I have Live Media Streaming enabled in my Connect instance.  I have tried re-deploying the stack but the issue persists.
