### ISSUE TITLE
400 API Responses in VM Portal 

### ISSUE THREAD

**Issue by PreciseSlice** [amazon-connect/voicemail-for-amazon-connect#14]
Hello, 

I have been working with this VM solution in multiple client accounts and my dev sandbox instance. Some versions deployed by me, some versions deployed by other devs. I am seeing similar errors across instances with the VM portal. 

Users (admins / managers) are reporting once they log into the VM portal and select the `sync` button nothing happens. In the console is am seeing `POST <base-url-redacted>/prod/agents/sync 400` `Uncaught (in promise) message: "400 - {errorMessage: "Unable to sync agents"}`. See image. I am seeing the same behavior, my user is in the admin and manager user pools and I have full permissions.

![sync](https://user-images.githubusercontent.com/20467500/80159745-fcb52d80-8588-11ea-8d9a-bff08d46b8dc.jpg)

Above issue is intermittent with a successful response some times. I did not deploy the cloud formation above the clients dev did however I did update the cloud formation to the latest after I saw there was a bug relating to syncing 100+ users. I have that patch and am still seeing issues. Again this is not isolated to one AWS instance or deployment of the template, have seen the behavior above in multiple deployments of the solution across instances, deployed by different devs.

I have also encountered more 400 api responses in the VM portal when attempting to download the contact flows from the VM portal. The below occurred with the solution deployed in my companies sandbox AWS instance. 

```
_stream_passthrough.js:33 POST <base-url-redacted>/prod/contact/flow 400
m._onFinish @ 2.88d196b9.chunk.js:1
(anonymous) @ 2.88d196b9.chunk.js:1
s.emit @ 2.88d196b9.chunk.js:1
C @ 2.88d196b9.chunk.js:1
S @ 2.88d196b9.chunk.js:1
(anonymous) @ 2.88d196b9.chunk.js:1
y.run @ 2.88d196b9.chunk.js:1
d @ 2.88d196b9.chunk.js:1
setTimeout (async)
s @ 2.88d196b9.chunk.js:1
i.nextTick @ 2.88d196b9.chunk.js:1
nextTick @ 2.88d196b9.chunk.js:1
(anonymous) @ 2.88d196b9.chunk.js:1
onwrite @ 2.88d196b9.chunk.js:1
m._write @ 2.88d196b9.chunk.js:1
v @ 2.88d196b9.chunk.js:1
(anonymous) @ 2.88d196b9.chunk.js:1
g.write @ 2.88d196b9.chunk.js:1
G.write @ 2.88d196b9.chunk.js:1
e @ 2.88d196b9.chunk.js:1
(anonymous) @ 2.88d196b9.chunk.js:1
(anonymous) @ 2.88d196b9.chunk.js:1
p @ 2.88d196b9.chunk.js:1
r @ 2.88d196b9.chunk.js:1
postMessage (async)
n @ 2.88d196b9.chunk.js:1
u.setImmediate @ 2.88d196b9.chunk.js:1
G.init @ 2.88d196b9.chunk.js:1
e.request.Request.init @ 2.88d196b9.chunk.js:1
G @ 2.88d196b9.chunk.js:1
s @ 2.88d196b9.chunk.js:1
value @ main.1ec94631.chunk.js:1
(anonymous) @ main.1ec94631.chunk.js:1
Promise.then (async)
value @ main.1ec94631.chunk.js:1
value @ main.1ec94631.chunk.js:1
value @ main.1ec94631.chunk.js:1
(anonymous) @ main.1ec94631.chunk.js:1
(anonymous) @ 2.88d196b9.chunk.js:1
download @ main.1ec94631.chunk.js:1
handleDownload @ main.1ec94631.chunk.js:1
s @ 2.88d196b9.chunk.js:1
d @ 2.88d196b9.chunk.js:1
(anonymous) @ 2.88d196b9.chunk.js:1
b @ 2.88d196b9.chunk.js:1
ot @ 2.88d196b9.chunk.js:1
it @ 2.88d196b9.chunk.js:1
st @ 2.88d196b9.chunk.js:1
dt @ 2.88d196b9.chunk.js:1
L @ 2.88d196b9.chunk.js:1
F @ 2.88d196b9.chunk.js:1
Yt @ 2.88d196b9.chunk.js:1
Zt @ 2.88d196b9.chunk.js:1
t.unstable_runWithPriority @ 2.88d196b9.chunk.js:1
Gi @ 2.88d196b9.chunk.js:1
M @ 2.88d196b9.chunk.js:1
Qt @ 2.88d196b9.chunk.js:1
contact-flow.reducer.ts:42 Uncaught (in promise) TypeError: Cannot read property 'message' of undefined
    at Le (contact-flow.reducer.ts:42)
    at transitions.js:49
    at f (redux.js:515)
    at index.js:165
    at dispatch (_stream_duplex.js:104)
    at contact-flow.actions.ts:78
```

I have a .mp4 clip of the above happening. I can send it if its helpful. Screenshot below:

![flow-error](https://user-images.githubusercontent.com/20467500/80159113-6df3e100-8587-11ea-873a-df142ac7a62f.PNG)

Let me know if you have any insights or if I can provide further information. AWS Support tickets are being opened by clients as well.

Thank you for your time,

**Comment by efh365** [comment]
Hi,

Thank you for reporting these issues. For the Contact Flow one, can you verify that you have a Queue called "BasicQueue" in your instance? That is the Fallback Queue parameter in the pop up. If that queue doesn't exist, the contact flow will fail to download.

For the sync agents issue, are you able to send the logs from CloudWatch? That will give me more insight. They will be in the function with "SyncRequest" in the name.

**Comment by PreciseSlice** [comment]
Thank you for looking into this. Yes, in the case of the call back flow I checked to see if the BasicQueue existed in the call flow after reading that was needed in the Cloud Formation deployment guide. The BasicQueue was there. I will get you the cloud watch logs and report back at some point today.

**Comment by efh365** [comment]
I found the bug with the other issue. If you update 'users' to 'list' here it should fix your problem.
https://github.com/amazon-connect/voicemail-for-amazon-connect/blob/master/source/aws-connect-vm-serverless/src/service/connect.service.js#L101

Let me know if that works for you. We will work on getting a fix out for this.

**Comment by PreciseSlice** [comment]
Thank you for the update. I am on a call at the moment but once I get the opportunity I will make the update and report the result.

**Comment by efh365** [comment]
You will also need to add 'return' to that line. So it should be: 
return this._listConnectUsers(list, nextToken, retry + 1);

**Comment by PreciseSlice** [comment]
I have other AWS personnel involved with this issue. The problem in the sync file was edited directly in the lambdas deployed by this template by another dev before I got to your suggestion. I do not want to update the source code and redeploy the template pointing to a local edited version of the Cloud Formation. The Cloud Formations stacks I am maintaining are pointed to `https://s3.amazonaws.com/solutions-reference/voicemail-for-amazon-connect/latest/voicemail-for-amazon-connect.template` . This is becoming a bit of a source code management mess. Since users are reporting sync is working now I am not going to make any further edits.

I am sure you are planning on doing so but please update this repository, its change log and your Cloud Formation template. Once that is done anyone using this solution can simply update their stack in Cloud Formation. Feel free to close the issue once that is done. Thank you for your help.

**Comment by yetig13** [comment]
Hi, we've been facing the exact same problem. Is this fix going to be applied to the repo & template soon? We do not wish to edit the source code directly on Lambda.

**Comment by KonstantinosCA** [comment]
I am experiencing the same issue... I created the stack and deleted 20 times almost and now it keeps rolling back and getting deleted in Cloudformation. Any help would be appreciated

**Comment by KonstantinosCA** [comment]
@PreciseSlice do you know what changes they made in the Lamdas? I am experiencing the same issue. 


Thanks,

**Comment by PreciseSlice** [comment]
> @PreciseSlice do you know what changes they made in the Lamdas? I am experiencing the same issue.
> 
> Thanks,

It was a while back but I believe editing this line as pointed out by efh365 above solved the problem. Quote below:

" I found the bug with the other issue. If you update 'users' to 'list' here it should fix your problem.
https://github.com/amazon-connect/voicemail-for-amazon-connect/blob/master/source/aws-connect-vm-serverless/src/service/connect.service.js#L101  "

@efh365  Why has a pull request to make this change not been opened? Why is a know issue affecting users of this repository where the solution has been identified being allowed to persist for months? Please update the source code of this repo so we can all update our Cloud Formation stacks in the instances where we have this VM system deployed. If I am wrong and the repository has been updated then please close this issue.

**Comment by efh365** [comment]
Sorry for the delay here. There is a long process to make updates to this solution. This fix has been pushed.
