### ISSUE TITLE
Distortion in WAV files

### ISSUE THREAD

**Issue by DrVoIP** [amazon-connect/voicemail-for-amazon-connect#17]
We have a Connect instance in Sydney region with agents in both the US and Austria.  We are running the Voice Mail application as published.   We note that the wav files that are played to us when we click a link in the VM sent to us, is virtually useless as it is so choppy as t be unintelligible.    My VoIP experience tells me that the file might be played across the internet and that may be the root cause.  However, if I go to the S3 bucket and download the wav file it is still distorted indicating that the file itself is recording as distorted.    So it is not just transmission over the internet that is the problem, but the SIP trunks to the instance are not applying QOS to the inbound leg.  Is anyone else reporting this?  It seems Region specific as we do not have that same result in several US regions? What can be done to improve this?

**Comment by ranman** [comment]
Hi @DrVoIP 

I wasn't able to reproduce your results.

My scenario:
Instance: Connect instance in ap-southeast-2 (Syndey)
Number: Australia number

Dialers:
iPhone X in US - no chop
google voice in EU - no chop
Skype in ?? - no chop

Do you have any additional data you can provide about your setup?

If you're not comfortable sharing in a github issue you're welcome to email me randhunt at amazon  dot com

**Comment by DrVoIP** [comment]
Hi Randal!  Aside from just sending you the wav files there is not much more data.  What I am hearing you say is this is not being experienced by anyone else, so it is specific to this instance.  From a trouble shooting perspective,  the wav files are being recorded with the audio drop out and not the result of moving files over the internet.  I have about 6 of these VM implementations and none of the others have this issue, though I can reproduce this behavior at will on this instance.  I am going to try attaching a new phone line and see if that has any impact.  In your scenario you did not attach a US number to the Sydney instance.

**Comment by ranman** [comment]
Thanks for the info. I’ll attempt to reproduce with a US number on the Sydney instance.

**Comment by DrVoIP** [comment]
[voicemail.wav.zip](https://github.com/amazon-connect/voicemail-for-amazon-connect/files/4589180/voicemail.wav.zip)
here is a sample wav right from the s3 bucket.  I also note we dont get transcriptions. checking the transcription service, the jobs are there but TEXT is empty or spotty, so I think it is failing.

**Comment by DrVoIP** [comment]
closing this out as I figured this out.  The issue is resolved by direct call to the phone numbers on the instance.  Unkown to me, the callers are dialing another number that is forwared to the numbers on the instance.  Once I know that, It was a short step to the answer!  Thank you to all, and maybe this will help someone else.

**Comment by jspronk** [comment]
In your VM-Agent call flow(assuming you're using the stock call flows), can you check your "Start media streaming" and make sure only "From customer" is checked?

**Comment by DrVoIP** [comment]
What we notice is that we attached another number to the instance and the results are more than acceptable.  This would indicate a carrier issue.  We have no visibility to the carrier, but after trial and error, we note changing out the phone number with another number clears the problem, eliminating the connectivity fulling back the wav file to the user as an issue.  It also proves out the configuration as working.

**Comment by DrVoIP** [comment]
The more of these solutions that we deploy the more I run into this issue.  As a VoIP engineer, I see it as a QOS issue either in the link between the SIP provider and the AWS SBC or a lack of QOS on the link between the SBC and the Instance.   The wav file is distorted at the point of recording, we know this by downloading the file from the S3 bucket directly.  So it is not a transport issue from S3 to destination.    Changing the in bound number often fixes this issue, but in many cases the number is published to a customer base and can not be easily changed. I have examples of this across different regions.

**Comment by efh365** [comment]
Thanks for reporting this. I am looking into this and will get back to you

**Comment by efh365** [comment]
DrVOIP - can you check what your "analytics and recording behavior" contact flow block is set to? Is it set to enable recording for both the agent and the customer or just for the customer?

**Comment by DrVoIP** [comment]
This appears to be set incorrectly and that seemed to fix the issue.  That still did not explain why this error only happened on one set of numbers and not another, but this change fixed this issue.
