### ISSUE TITLE
New Feature Requests: Voicemail option only when agents are offline and single voicemail location

### ISSUE THREAD

**Issue by jennsanchez** [amazon-connect/voicemail-for-amazon-connect#18]
I have installed your Voicemail for Amazon Connect stack and all is working great so far! We love receiving the emails with the message transcription. I am writing at the suggestion of Amazon support who I opened a case with, looking to customize the solution. 

First, we are only looking to provide the voicemail option when agents are not online (during the lunch hour or after work hours). We would like to integrate the voicemail functionality into our existing contact flow to be executed if there are no available agents to take the call. If this can be done as a transfer to contact flow operation, then we could add the voicemail feature as a terminating event given a number of failure conditions, which would simplify and standardize our contact flows.

Second, our use case is different in that we have a small customer service center where most callers do not know the extension of a particular agent. We were hoping to route all calls to one group voicemail box which can be checked by whoever is the first agent in the office the next morning. Perhaps this could be done by creating a "voicemail" user with a communal email address (which we have) to which all calls are routed. We could skip the customer input (extension) and the lambda data dip and provide the parameters/attributes necessary to perform this operation.

Perhaps there are others out there with a similar use case who would also benefit from these additional features.

Many thanks!

**Comment by DrVoIP** [comment]
We have been able to use LEX as a solution when folks do not know the extension number.  We create a database/lambda to take LEX.intent in and match name with extension number, the insert the extension number as a contact attribute which the follows the same call flow as the original.  We use this to create queue based voice messages as well.  So if the CustomerService queue is closed, we set an extension number in a contact attribute and pass it back in to a modified call flow that does not prompt for extension number as we are passing it in.   You have to create a user named CustomerService and give it an email address.   Works just fine!
