### ISSUE TITLE
Change the transcription language to spanish

### ISSUE THREAD

**Issue by esudasassi** [amazon-connect/voicemail-for-amazon-connect#2]
Hi guys! Thanks for the voicemail stack, it worked like a charmed and I have installed it on our connect instance.

Everything works fine with the voicemail solution, we are able to get the sms and email with the link to the audio file and the the transcription just fine as long as the voice message is left in english, but we handle only spanish callers. 
Could you can please point me to where I could configure the transcription language? Not a developer but I have some AWS training.

Thanks for your time!

Eduardo

**Comment by efh365** [comment]
Hi Eduardo, 

Im glad it is working well for you! If you want to change the language to Spanish, you can do so by setting an attribute in your VM-Greeting contact flow called 'languageCode'. The potential values for the language code are detailed here: https://docs.aws.amazon.com/transcribe/latest/dg/what-is-transcribe.html

Thanks!

**Comment by esudasassi** [comment]
Hi! Thanks for the help, I tried setting the attribute at the beginning of the VM-greet CF, please see attached files. When I tried calling the voicemail now it acts as if the voicemail is being recorded but the email and SMS are not sent anymore.

Can you help me identify what I did wrong please?

Thanks!

Eduardo
![Screen Shot 2020-04-07 at 12 20 05 PM](https://user-images.githubusercontent.com/63131478/78724450-bb672180-78ea-11ea-887e-d5360cbc6ede.png)
![Screen Shot 2020-04-07 at 12 19 31 PM](https://user-images.githubusercontent.com/63131478/78724452-bd30e500-78ea-11ea-8ba4-38dc37a1131b.png)

**Comment by esudasassi** [comment]
> Hi Eduardo,
> 
> Im glad it is working well for you! If you want to change the language to Spanish, you can do so by setting an attribute in your VM-Greeting contact flow called 'languageCode'. The potential values for the language code are detailed here: https://docs.aws.amazon.com/transcribe/latest/dg/what-is-transcribe.html
> 
> Thanks!

Hi! Can you help me out? i uploaded the screen captures of how I tried to add the attribute, but it stopped working completely.

Thanks a lot!

**Comment by efh365** [comment]
Hi Eduardo,

You need to set the contact attribute block to 'Use Text' instead of 'Use attribute'. Right now it is setting the language code to another attribute called 'es-US'. This should fix your problem

**Comment by esudasassi** [comment]
> Hi Eduardo,
> 
> You need to set the contact attribute block to 'Use Text' instead of 'Use attribute'. Right now it is setting the language code to another attribute called 'es-US'. This should fix your problem

Thank a lot! That was it, i got it working now in spanish.
