### ISSUE TITLE
Voice Portal React JS Error

### ISSUE THREAD

**Issue by startupwolf** [amazon-connect/voicemail-for-amazon-connect#20]
Hello, today we have followed the deployment guidelines (https://docs.aws.amazon.com/solutions/latest/voicemail-for-amazon-connect/deployment.html) and in general things look fine, but the voice portal does not load correctly. After Cognito login only a white page is shown and the following React console error:

`TypeError: Cannot read property 'includes' of undefined
    at Function.mapToProps (NavigationBar.js:153)
    at n (connect.js:82)
    at Function.n.mapToProps (connect.js:89)
    at n (connect.js:81)
    at jss.esm.js:74
    at selectorFactory.js:24
    at Object.useMemo (react-dom.production.min.js:4267)
    at t.useMemo (react-dom.production.min.js:276)
    at C (selectorFactory.js:62)
    at Wa (react-dom.production.min.js:3913)
    at Oo (react-dom.production.min.js:4352)
    at qo (react-dom.production.min.js:4342)
    at Do (react-dom.production.min.js:4329)
    at fs (react-dom.production.min.js:7025)
    at cu (react-dom.production.min.js:1572)
    at su (react-dom.production.min.js:1572)
    at Xs (react-dom.production.min.js:6180)
    at react-dom.production.min.js:3124
    at t.unstable_runWithPriority (bluebird.js:252)
    at Gi (react-dom.production.min.js:3104)
    at Ki (react-dom.production.min.js:3121)
    at $i (react-dom.production.min.js:3118)`

Any idea why this occurs and how it can be fixed?

**Comment by efh365** [comment]
Hi. Can you verify whether your Cognito user is in the Manager and/or Admin user pool group? We have a bug where the page is blank after log in if the user is not in either of those groups. We are working on deploying a fix in the coming weeks.

**Comment by startupwolf** [comment]
Hi. Thank you, it really was the case, that some new users that I had created for testing where not correctly assigned (I have created them because I did not receive the initial password for the automatically created users). So the page is now shown correctly, yet the agent sync fails with this error:
`
POST https://1ur5mq5ond.execute-api.eu-central-1.amazonaws.com/prod/agents/sync 400
login:1 Uncaught (in promise) i {name: "StatusCodeError", statusCode: 400, message: "400 - {"errorMessage":"Unable to sync agents"}", error: {…}, options: {…}, …}
`

Same is the case for download of the contact flow:
`
POST https://1ur5mq5ond.execute-api.eu-central-1.amazonaws.com/prod/contact/flow 400
contact-flow.reducer.ts:43 Uncaught (in promise) TypeError: Cannot read property 'message' of undefined
`

I hope to also find the root cause for this :)

**Comment by efh365** [comment]
If both those cases are failing, it is probably due to the fact that you entered the Amazon Connect instance arn into the CloudFormation parameters instead of the instance id. The id is just the UUID at the end of the arn. You can run an update stack operation if that is the case. Also check that you deployed the stack in the same region as your instance

**Comment by startupwolf** [comment]
Hello, thanks. It was not ARN, but still not fully correct UUID. I have run an update stack operation and now it works correctly. I have also recreated the initial admin/manager user via an update stack operation and also received the initial temporary password mails. So everything is fine now. Thank you for your help. I will close this issue.
