### ISSUE TITLE
No Email Address fo SSO

### ISSUE THREAD

**Issue by DrVoIP** [amazon-connect/voicemail-for-amazon-connect#22]
When using this application on instances that use SSO, there is no field in the user record for an email address.  How do you send email to these agents?  Can you directly edit the dbase to add the email?

**Comment by efh365** [comment]
The logic for SSO instances right now is to send an email to the username assuming the username is the email address. If the email address is not the username, you can update the code here to pull the value you are looking for:

 https://github.com/amazon-connect/voicemail-for-amazon-connect/blob/master/source/aws-connect-vm-serverless/src/service/notification.service.js#L56

**Comment by DrVoIP** [comment]
FirstName, LastName, LoginName are the fields in a USER definition in an instance with SSO.  So when you say "username" which field are you expecting the email address to be in?   If we modify the code, which function is this code in?

**Comment by efh365** [comment]
I am referring to login name. The updated code should be uploaded in the ContactVoicemailStream Lambda Function
