### ISSUE TITLE
Can't download the contact flows from the portal

### ISSUE THREAD

**Issue by mshaaba1** [amazon-connect/voicemail-for-amazon-connect#24]
Hi There,
After logging into the Amazon Connect Voicemail Management Portal, then opened the setting, I found the download button is disabled. So I can't download the VM-Agent.json and VM-Greeting.json files for contact flow. Not sure if I missed something. Appreciate your help.
![image](https://user-images.githubusercontent.com/53372616/86887572-1bfd3900-c13c-11ea-8df9-660d51ab4a96.png)

Regards,
Mohab

**Comment by swalmsley11** [comment]
Are you logging in with a user in the Admin group? When deploying the Cloudformation template did you input two separate users/email addresses for the Admin and Manager?

**Comment by mshaaba1** [comment]
I used the same email address for simplicity, would that create a problem? Anyways, I missed one of the most important steps at the beginning, which is to create the S3 bucket that has the resources. Still working on getting it done as I am getting errors from the cloudformation now.

**Comment by efh365** [comment]
hi, if you used the same email address, your user most likely only has the manager permissions. if you go to the cognito console, make sure your user is in both the manager and admin group

**Comment by mshaaba1** [comment]
Hi There,
I am still struggling in with this solution. First I have run the template "aws-connect-vm.template" and after a lot of issues, I was able to create the stack. I had the impression that the cloud front stack should be created as part of the template, but that was not the case. So I tried to create the stack "voicemail-for-amazon-connect.template" as per the PDF document, but it is failing in the middle while creating the voicemailstack and it is not giving me a reason for the failure. Appreciate your recommendation. I am not sure, what I have missed.

**Comment by efh365** [comment]
Have you followed the implementation guide here? https://aws.amazon.com/solutions/implementations/voicemail-for-amazon-connect/

You can deploy the stack from that link. The root stack that is deployed is from voicemail-for-amazon-connect.template. aws-connect-vm.template is one of the sub stacks. The implementation guide also has specific instructions as to what each field should be. I would look through that in case you are missing something in the input parameters.

**Comment by mshaaba1** [comment]
Yeah, thanks, tried to follow it, several times, didn't work. Like I was able to create the portal but couldn't actually find the contact flows. So, one final request. As I can't download the contact flows vm-greeting.json and vm-agent.json, could you please upload them to the github.
Thanks.

**Comment by efh365** [comment]
The contact flows are available in the settings, which you can access in the upper righthand corner of the portal. Make sure you are logged in with the admin user. since you used the same email for admin and manager, the user is actually the manager. You will need to go to the AWS Cognito console and modify the user to have both the Admin and Manager groups.

The contact flows are available in this lambda function: https://github.com/amazon-connect/voicemail-for-amazon-connect/blob/master/source/aws-connect-vm-serverless/src/service/contact-flow.service.js

**Comment by efh365** [comment]
Closing this issue. Please re-open if you have further questions.
