### ISSUE TITLE
AWS::Lambda::Function does not like \n in Description

### ISSUE THREAD

**Issue by nbrational** [amazon-connect/voicemail-for-amazon-connect#26]
https://github.com/amazon-connect/voicemail-for-amazon-connect/blob/8c6a3eda8929ba4e0984e7694b1a59bec25b27a4/deployment/aws-connect-vm.template#L121

Creation of resource GetAgentByExtensionLambdaFunction fails with error: 
`
1 validation error detected: Value 'AWS Lambda test' at 'description' failed to satisfy constraint: Member must satisfy regular expression pattern: .* (Service: AWSLambdaInternal; Status Code: 400; Error Code: ValidationException; Request ID: e4b06017-d6b1-4414-9aae-98f2b7690ea4)
`

Template to replicate is attached.
[LambdaTemplate.txt](https://github.com/amazon-connect/voicemail-for-amazon-connect/files/4894277/LambdaTemplate.txt)

**Comment by dfw100** [comment]
@nbrational I deployed the voicemail solution without any issues. Could you please redeploy and let us know how it goes?

**Comment by khastation** [comment]
@nbrational are you still facing this issue?
