### ISSUE TITLE
Sanity Check

### ISSUE THREAD

**Issue by DrVoIP** [amazon-connect/voicemail-for-amazon-connect#28]
Is the Database updated as you add extensions and details in the admin interface as you add them? Or do you need to save, refresh or sync to update the database?

**Comment by swalmsley11** [comment]
Yes, the admin portal updates the dynamoDB table as you add/update fields for the users (such as extensions). The sync is a function that occurs automatically every 24 hours to pull agent information from Connect into the DB. If you add/remove users and want to see them updated in the Voicemail admin portal you will manually run the Sync function.
