### ISSUE TITLE
Recording bypass and LENS impact

### ISSUE THREAD

**Issue by DrVoIP** [amazon-connect/voicemail-for-amazon-connect#29]
Do I understand that callers who reach an Agent by Extension number are not recorded and there does not seem to be an option to enable recording.  For this reason LENS will not be aware of direct to agent calls as well?

**Comment by dfw100** [comment]
I am trying to understand your question better. The contact flow (VM-Agent) streams the call audio from the customer to the Kinesis Video Stream (KVS). Voicemail solution then retrieves that audio from KVS to create an audio file. pre-signed URL of that file is delivered to the agent. 

Contact Lens is only for calls between the customer and agent. So if you want to use contact lens you just need to add the 'Set recording and analytics behavior' block and enable contact lens. That’s completely separate from the KVS audio streaming block. 

Please let me know if you have more questions.

**Comment by efh365** [comment]
Hi DrVoIP, do you have any further questions here?

**Comment by DrVoIP** [comment]
IF someone calls in and heads off to Extension 1234 and that agent is not available, the caller is shuttled to the contact flow for recording the media stream for voice mail.    The question has to do with if the Agent is available,  I Just want to confirm I can add LENS to the contact flow that supports VM application and that call like any other contact flow will be recorded if set along with the analytics option.   Just verifying that there is no reason that a call completed by directly routing to an Agent cant be recorded!  Thank you for all you do!

**Comment by efh365** [comment]
Thanks for the clarification. You can enable Contact Lens on the calls by adding the Recording block to the Contact Flow and enabling Contact Lens. Contact Lens analysis will only be done once the agent and customer are connected if the agent is available.
