### ISSUE TITLE
Template fails on reserved names in User Pool Domain Prefix field

### ISSUE THREAD

**Issue by slate104** [amazon-connect/voicemail-for-amazon-connect#3]
Templates fail due to using reserved names in User Pool Domain Prefix field ie Amazon, or Cognito. Should add validation or tooltip to avoid usage. Also reason for failure was not clear, had to dig through cloudtrail.

**Comment by efh365** [comment]
Thanks for bringing this to my attention. We will update the documentation to be more clear.

**Comment by slate104** [comment]
I would also fix the Connect ID field to add some validation and/or give better documentation stating that you’re just looking for the GUID and not the whole ARN. Thank you for this package though. Overall great architecture and nice solution. I have some things I’ll add.
