### ISSUE TITLE
No VM-Greeting.json is generated

### ISSUE THREAD

**Issue by sichen1234** [amazon-connect/voicemail-for-amazon-connect#30]
Hello, I followed the steps until I'm at the Step 4. Generate and Download Contact Flows

The screen looks the same as your screenshot, but it only generated a VM-Agent.json, which I was able to import into Connect.

There was no VM-Greeting.json generated.  Is there a separate step for generating this?

**Comment by dfw100** [comment]
Hi, The contact flow creation has a dependency on a queue named BasicQueue. Create a new queue, name it BasicQueue, then download the contact flow.

**Comment by dfw100** [comment]
Also, ensure browser is not blocking downloads.

**Comment by opentaps** [comment]
Hello, thanks for your response.  Yes, it did have the BasicQueue.  Is it ok if there is another queue or must it only have one BasicQueue?

Yes, the browser is allowing downloads.  I was able to download VM-Agent.json but there was no download for VM-Greeting.json  I tested in both Safari and Chrome with same results.

Also should there be any errors in the lambda function log?  This is what the log looks like.
![Screen Shot 2020-07-30 at 9 35 33 AM](https://user-images.githubusercontent.com/1706353/88949484-25178c80-d248-11ea-8b0d-5f8eb32629b9.png)

**Comment by dfw100** [comment]
Thanks for the quick reply. 
1. You can have other queues as well and that should not cause any problem.
2. Enable multiple downloads in browser and try . Here is how you do that in Chrome https://www.howtogeek.com/428416/how-to-enabledisable-multiple-file-downloads-in-chrome/ 
3. It contact flow download status doesn't reflect in lambda function log

Please try this and share results.

**Comment by sichen1234** [comment]
Hmm...It does not have this option to allow multiple downloads.  My Chrome is Version 83.0.4103.106 (Official Build) (64-bit)
![Screen Shot 2020-07-30 at 10 14 31 AM](https://user-images.githubusercontent.com/1706353/88953393-bd644000-d24d-11ea-912f-59ae0d3c931b.png)

**Comment by dfw100** [comment]
Thanks for sharing the results. I was able to reproduce the issue when the option "Automatic downloads Ask when a site tries to download files automatically after the first file" was turned off.  

Can you please try the following steps?

1. Turn it OFF (The text will change to "Do not allow any site to download multiple files automatically" when you turn it OFF)
2. Go to  Voicemail for Amazon Connect Management Portal and Refresh the page
3. Turn it ON (The text will change to "Automatic downloads Ask when a site tries to download files automatically after the first file" when you turn it ON)
4. Go to  Voicemail for Amazon Connect Management Portal and Refresh the page
5. Click the settings and try to download contact flows
![image](https://user-images.githubusercontent.com/65248270/88956353-db886b00-d262-11ea-8551-d32c2a2db354.png)

**Comment by sichen1234** [comment]
It worked!  Thank you so much!

**Comment by ahf85br** [comment]
Hey guys!

I cannot download M-Greeting.json and VM-Agent.json either. It looks there's a bug on Amazon Connect implementation.

Would it be possible to someone to make these files available somewhere?

Thanks

**Comment by ahf85br** [comment]
Wow! The reason why I could not download was because I changed the name of the queue. Make sure the name is BasicQueue in order to download it. It works now! :)
