### ISSUE TITLE
Should the last part of the Section 6 in documentation say VM-Greeting?

### ISSUE THREAD

**Issue by sichen1234** [amazon-connect/voicemail-for-amazon-connect#31]
Hello,

I got the voicemail working but am looking at https://docs.aws.amazon.com/solutions/latest/voicemail-for-amazon-connect/deployment.html

The last part of Section 6 right now says 
On the Edit Phone number page, select the Contact flow / IVR dropdown menu and choose Voicemail System to assign the Voicemail System contact flow to your chosen phone number.

Should it be "choose VM-Greeting"?

I did not see a "Voicemail System" option here, but after importing VM-Greeting.json it worked by choosing VM-Greeting.

**Comment by dfw100** [comment]
That's correct. Select **VM-Greeting** in the **Contact flow / IVR** dropdown as highlighted in the below screenshot.
![image](https://user-images.githubusercontent.com/65248270/89066956-f840a380-d333-11ea-876b-c87accd17324.png)

**Comment by sichen1234** [comment]
OK.  I'm glad I did the right thing.  Maybe you should consider changing the deployment documentation?
