### ISSUE TITLE
run build result issue

### ISSUE THREAD

**Issue by rybalko** [amazon-connect/voicemail-for-amazon-connect#32]
Hello, 
I tried to build application with

export DIST_OUTPUT_BUCKET=my-bucket-name
export SOLUTION_NAME=my-solution-name
export VERSION=1.0

./build-s3-dist.sh $DIST_OUTPUT_BUCKET $SOLUTION_NAME $VERSION

it looks like build finished successfully, except
message:
cp: -r not specified; omitting directory './.dist/aws-connect-vm-serverless/templates'
and result is in the
source/aws-connect-vm-portal/build
directory

I tried run
serve -s build
but http://localhost:5000 link redirected me to the 
https://__c_domain__/oauth2/authorize?redirect_uri=__C_REDIR__&response_type=code&client_id=__C_CLIENT_ID__&identity_provider=COGNITO&scopes=profile

Is something wrong with setup ?

**Comment by efh365** [comment]
the comment to omit the .dist directory is ok. why are you trying to run 'serve -s build'?

**Comment by khastation** [comment]
@rybalko first, and unrelated, but can you confirm that you've added the correct bucket name of a bucket you own in your solution. I ask becuase your comment has 'my-bucket-name' as the DIST_OUTPUT_BUCKET.

As per your question around the solution, you will need to run the CloudFormation template generated as a part of your build process once you've built the customized script (build-s3-dist.sh). Your resultant artifacts should be available in the deployment folder once the build is complete. 

Running 'serve -s build' will not deploy your solution in this case.

**Comment by efh365** [comment]
@rybalko do you still need help here?

**Comment by khastation** [comment]
@rybalko are you still facing issues here?

**Comment by rybalko** [comment]
Everything is working now. Thank you.

This issue could be closed.
