### ISSUE TITLE
How would customer find an Extension number of an agent?

### ISSUE THREAD

**Issue by swwapnilp** [amazon-connect/voicemail-for-amazon-connect#34]
Hi Team,

I was looking at the solution and got one really important question that why would customers remember the agent's extension number? How would customer know the agent's extension number? 

As you mentioned in your solution that you're taking the last **Four digits as extension number** from the dialled number so that means while performing sync agents in the management portal, do we need to add a same or different extension to all the agents?

Looking forward to discussing with you.

Regards,
Swapnil Pawar

**Comment by DrVoIP** [comment]
We prefer to use LEX to create a Dial by Name solution, avoiding publishing a directory.  - DrVoIP

**Comment by efh365** [comment]
yes, there is an option to make the solution grab the last 4 digits of the dialed number to direct calls to specific agents. this solution is meant to be a starting point for you. you can update it to direct to agents how you see fit. Yes, Lex is a great option to set up a dial by name approach.

if you want to do leave voicemails based on the dialed number then you will need to have a different phone number for each agent.

**Comment by khastation** [comment]
@spawar1991 do you still have any open questions?

**Comment by efh365** [comment]
@spawar1991 do you still need help here?

**Comment by khastation** [comment]
@spawar1991 please reopen this issue if there open items.
