### ISSUE TITLE
Only VM-Agent contact flow available for download

### ISSUE THREAD

**Issue by nolanc** [amazon-connect/voicemail-for-amazon-connect#35]
And it throws this message

Failed to import the contact flow because it is not the same type of flow as the one it is being imported into

Deployed from the latest CloudFormation template

This is in the SYDNEY region (Asia Pacific South East 2)

**Comment by efh365** [comment]
hi. please make sure you are creating a contact flow that is the same type as what you are importing. For example, on the main contact flow page you have to select the drop down to create a customer queue flow when you upload the flow for the customer queue.

https://docs.aws.amazon.com/connect/latest/adminguide/create-contact-flow.html
