### ISSUE TITLE
Error in ContactVoicemailStream Lambda

### ISSUE THREAD

**Issue by chrispiccaro18** [amazon-connect/voicemail-for-amazon-connect#36]
I'm getting the following error in the ContactVoicemailStream function: 
```
2020-09-25T19:16:16.951Z	78e2e835-69a2-413f-9a0f-23a88043f9c3	INFO	Error { ResourceNotFoundException: Resource not found
    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:307:13)
    at IncomingMessage.emit (events.js:203:15)
  message: 'Resource not found',
  code: 'ResourceNotFoundException',
  time: 2020-09-25T19:16:16.948Z,
  requestId: '4fb423f9-e55e-4e73-8559-5910d7fac53c',
  statusCode: 404,
  retryable: false,
  retryDelay: 91.01308082369519 }
```

Both the sending and receiving emails are verified with SES and the ContactVoicemailTable is getting contacted without a problem.

Can you point me in the right direction to resolve this?

**Comment by efh365** [comment]
Hi Chris. You are seeing a resource not found exception, which most likely means one of the inputs to your CloudFormation stack is incorrect and the resource that is being looked for cannot be found. I assume you are not receiving emails, right? It is hard to say from that one line, but it could be an invalid S3 bucket or amazon connect instance id. What are the logs right before the error?

**Comment by chrispiccaro18** [comment]
Correct, I'm not receiving emails. I was able to get emails sent with my own lambda based on the same triggers and permissions. Code [here](https://github.com/chrispiccaro18/customVMLambda) if you want to review. I'm only accessing the S3 bucket with the voicemail recordings.

The two logs after the START log and before the error are:
```
2020-09-30T19:54:44.846Z	55f748f7-e76b-4beb-86a1-2029b3dc727b	INFO	Processing Voicemail Recording
2020-09-30T19:54:44.847Z	55f748f7-e76b-4beb-86a1-2029b3dc727b	INFO	Getting Global Settings
```
This leads me to think it's an error with accessing the global table, but I've confirmed the environment variable for the global table in the lambda matches the actual table name in dynamoDB. The instanceArn in the table is also the correct Amazon Connect ARN.

It looks like the function is performing fine when the transcript is not ready (the first time the ContactVoicemail table gets updated). The only log between the START and END is `2020-09-30T19:54:44.846Z	55f748f7-e76b-4beb-86a1-2029b3dc727b	INFO	Processing Voicemail Recording`

An interesting note: I've set up a test for the function that mocks the event where the ContactVoicemail dynamoDB table gets updated when the transcript is finished (gist [here](https://gist.github.com/chrispiccaro18/85c4b313cd9387ab24d3324260b54ea8)) and there was once where the function succeeded (with email sent) but I'm unable to replicate that.

**Comment by efh365** [comment]
Thanks for the additional information. This is going to be quite hard to debug without additional logs. Can you add log statements, rebuild the code, and upload it to Lambda to test again? There could be a number of places where a resource is undefined:

- DDB table is incorrect (seems to not be the case)
- The Connect arn (verify the arn is correct in the env variables)
- The agent user id doesnt exist anymore
- The voicemail recording bucket name is incorrect
- The voicemail recording path prefix is incorrect
- The transcription job is invalid

Any of those could fail too if you have cross region resources. By default, this should all work so I dont know what is happening in this case and why something is off. Can you test the solution end to end with encryption and transcription disabled so we can try to knock off a few items? And then try sending it to only email and then try only SMS.

**Comment by chrispiccaro18** [comment]
Thanks for taking the time to look at this. For the logging/rebuilding, is the best way to do that [building the distributable](https://github.com/amazon-connect/voicemail-for-amazon-connect#building-distributable-for-customization) in the readme? What's your dev setup for this project? Are you using [SAM](https://aws.amazon.com/serverless/sam/)?

I created a fresh AWS business account and made sure to deploy only in one region us-west-2. I'll let you know what happens after I go through a few e2e tests.

Also, not sure if I should open a separate issue but it might be related: toggling encrypt in the cloudfront front end doesn't seem to work. The modal reflects the change but the table in the UI and the dynamoDB table don't register the change See gif:
![cloudfront-bug](https://user-images.githubusercontent.com/41354343/94849325-13826a80-03da-11eb-890d-ddcadbc218c6.gif)

**Comment by khastation** [comment]
@chrispiccaro18 do you have any updates based on the end to end tests you were looking to complete?
Also, please open a separate issue for the modal bug, it helps us track it better. Thank you for reporting it!

**Comment by chrispiccaro18** [comment]
I haven't had time to do the tests and I've been using a workaround that's doing just fine for now (basically replacing the ContactVoicemailStream Lambda function). I do want to get to it eventually but am having trouble with finding the best solution to test. What's your dev setup for this project? Are you using [SAM](https://aws.amazon.com/serverless/sam/)?

**Comment by efh365** [comment]
Regarding the encryption snippet you are showing - if you have encryption enabled globally, you cant disable it on an individual person. Can you check your global config? (We did that as there are manager and admin personas - admin controls global and manager can only control each person)

We user a serverless to test and deploy the backend. you can find deployment instructions [here](https://github.com/amazon-connect/voicemail-for-amazon-connect/tree/master/source/aws-connect-vm-serverless). the frontend is deployed with our own scripts. there are instructions to test the portal [here](https://github.com/amazon-connect/voicemail-for-amazon-connect/tree/master/source/aws-connect-vm-portal).

The main commands run to deploy the serverless piece are listed [here](https://github.com/amazon-connect/voicemail-for-amazon-connect/blob/master/deployment/build-s3-dist.sh#L76).

Let me know what specific questions you have in the deployment process if you need help.

**Comment by khastation** [comment]
@chrispiccaro18 do you still have any other questions about the deployment process?
