### ISSUE TITLE
Cannot create stack error

### ISSUE THREAD

**Issue by jack-newbury** [amazon-connect/voicemail-for-amazon-connect#38]
When attempting to bring up the stack in EU-west-2 i keep getting the following errors.

Embedded stack arn:aws:cloudformation:us-east-1:430742536651:stack/aws-connect-6103-voicemail-CopyLambdaArtifactsStack-FI4YHJYYTON9/edfdb970-093f-11eb-a6a3-1208f0f76cbf was not successfully created: CustomResource attribute error: Vendor response doesn't contain JarVersionId key in object arn:aws:cloudformation:us-east-1:430742536651:stack/aws-connect-6103-voicemail-CopyLambdaArtifactsStack-FI4YHJYYTON9/edfdb970-093f-11eb-a6a3-1208f0f76cbf|CopyObjects|455cba8f-9dc2-4fc5-a6c2-bd05b0afcc0c in S3 bucket cloudformation-custom-resource-storage-useast1

The following resource(s) failed to create: [CopyLambdaArtifactsStack]. . Rollback requested by user.

Can someone shine some light on what this actually means and a potential resolution

**Comment by efh365** [comment]
@jack-newbury how are you deploying the stack? It looks like you are trying to deploy a us-east-1 stack in eu-west-2, which is why it is failing

**Comment by khastation** [comment]
@jack-newbury let us know details of your stack so that we can investigate.

**Comment by angelacyu** [comment]
resolving this issue, since it has been inactive for the last few months
