### ISSUE TITLE
Portal UI does not work when template is deployed in US-West-2

### ISSUE THREAD

**Issue by slate104** [amazon-connect/voicemail-for-amazon-connect#4]
I've deployed in both East-1 (successfully), and West-2 (successfully) however the Portal UI does not work in West-2 but works fine in East-1. My connect deployment is in West-2, hence the need to deploy this in West-2. Haven't been able to find the problem yet.

**Comment by efh365** [comment]
Hi slate, 

Can you please add any more details here? What is showing when you go to the cloudfront url?

**Comment by slate104** [comment]
It gives a access denied error. Looks like you hit cloudfront and it never sends you to cognito for auth. S3 URL is there and access denied. It actually cleared up after about 2 hours and started working. Not sure what the delay is. Maybe cloudfront although it was done distributing in cloudfront long before it started working.

**Comment by efh365** [comment]
Oh yes, that is what happens when the cloudfront domain isnt ready yet. The redirection to S3 is expected until the domain is ready. Im glad it is working!
