### ISSUE TITLE
Split Kinesis Contact Trace Record & Agent Events Streams 

### ISSUE THREAD

**Issue by terrell-r** [amazon-connect/voicemail-for-amazon-connect#41]
Hello, 

I'm currently using the same Kinesis Stream for both Contact Trace Records, and Agent Events. Is it possible to split these into two separate streams? 

Use case: I'm looking to split the Kinesis Streams to make SIEM searching easier. I'm Currently using voicemail solution with the agent direct dial Lambda function. 

Reference: 
"Agent event streams are not enabled by default. Before you can enable agent event streams in Amazon Connect, create a data stream in Amazon Kinesis Data Streams. Then, choose the Kinesis stream as the stream to use for agent event streams. Though you can use the same stream for both agent event streams and contact trace records, managing and getting data from the stream is much easier when you use a separate stream for each."
https://docs.aws.amazon.com/connect/latest/adminguide/agent-event-streams-enable.html

**Comment by DrVoIP** [comment]
If I understand the question, you can use Kinesis Fire hose to make this work.  Additionally, a  kinesis stream can be shared by multiple functions.

**Comment by efh365** [comment]
Yes, DrVoIP is right here. You can use a separate stream for the two functions. Do you need any other help with this?

**Comment by khastation** [comment]
@DrVoIP Do you still need help with this issue?
