### ISSUE TITLE
tests/notifications.test.js missing process.env.SECRET_ARN

### ISSUE THREAD

**Issue by FarOutWest** [amazon-connect/voicemail-for-amazon-connect#44]
Hi. I'm trying to run the testing suite before modifying anything for custom email notifications and I notice that the file `/voicemail-for-amazon-connect/source/aws-connect-vm-serverless/src/service/s3.service.js` references the environment variable `process.env.SECRET_ARN`. However, when I look in the testing environment file found at `voicemail-for-amazon-connect/source/aws-connect-vm-serverless/tests/env.js` there is no entry for `process.env.SECRET_ARN`. I'm curious if this is a misnaming or if I need to configure something else in order to verify the functionality of these tests? Or is there some other setup I need to complete in order to test the notifications? 

Thanks.

**Comment by FarOutWest** [comment]
I guess after further investigation into the `tests/notifications.test.js` it isn't even testing the `sendMail` function so I will just have to build that myself. My question regarding the missing environment variable still stands, however.

**Comment by angelacyu** [comment]
I would add the variable to the env file yourself. Thanks for finding this, I'll add it to our backlog

**Comment by FarOutWest** [comment]
Awesome yeah, I was able to get this all working with some tweaks and digging. This issue can be closed. Thanks for your help.
