### ISSUE TITLE
ContactId Not found Error from Kinesis datastream

### ISSUE THREAD

**Issue by continuuminnovations** [amazon-connect/voicemail-for-amazon-connect#45]
Followed all the mentioned in the documentation  but getting the below error while executing the KvsProcessRecordingLambda function. Please help if i am missing any configuration.

org.json.JSONException: JSONObject["ContactId"] not found.

**Comment by efh365** [comment]
Hi. I believe this is because the agent event stream is also consumed. if you disable the agent event stream from going to that lambda function the error should be resolved

**Comment by continuuminnovations** [comment]
it is because of the stream issue. where is the source code for the KvsProcessRecordingLambda function?
