### ISSUE TITLE
Portal Configuration Broken Outside us-east-1

### ISSUE THREAD

**Issue by chriscoombs** [amazon-connect/voicemail-for-amazon-connect#47]
The parent stack passes the non-regional S3 endpoint to the CloudFront configuration, as such attempting to load the portal results in an unauthorised error when deployed in a region other than us-east-1.

**Comment by angelacyu** [comment]
Hi, I deployed the solution using Cloudformation with the template source as "Amazon S3 URL" with the value "https://s3.amazonaws.com/solutions-reference/voicemail-for-amazon-connect/latest/voicemail-for-amazon-connect.template" as given on the AWS Solutions page. I was able to deploy in us-west-2 and access the portal. Can you give this a try?

**Comment by chriscoombs** [comment]
I have attempted to launch the stack as per your instructions in us-west-2 but I received the same error (screenshot below) as was reported to me, and I verified, in ap-southeast-2.

In your testing are you deploying a new stack and immediately checking the CloudFront distribution URL after the CloudFormation stack reports as complete? The issue does resolve itself after several minutes (from reading the AWS forums it appears to be due to internal DNS propagation lag), but anyone launching the stack and then immediately loading the portal outside of us-east-1 will see an error like the one in the screenshot below.

![error](https://user-images.githubusercontent.com/2349452/104659031-0b93cf80-5718-11eb-87b7-a5cfd608c0b0.png)

**Comment by angelacyu** [comment]
Please see this paragraph in the deployment guide:

You can view the status of the stack in the AWS CloudFormation console in the Status column. You should see a status of CREATE_COMPLETE in approximately 30 minutes. However, depending on the AWS Region in which you deployed the stack, **it may take additional time beyond the 30 minutes for the CloudFront distribution to create and populate the Amazon Connect Voicemail Management Portal.**

https://docs.aws.amazon.com/solutions/latest/voicemail-for-amazon-connect/deployment.html#step3

**Comment by chriscoombs** [comment]
@angieyu I think we should be looking to meet a higher standard than a statement in the deployment guide. This is a real issue, reported to me by multiple customers which needs resolving. Please re-open.

**Comment by angelacyu** [comment]
I think its quite reasonable to allow assets time to finish deploying and the time expectation is outlined in the documentation. If I am missing any information, then please provide further.
