### ISSUE TITLE
VoiceMailPortalStack fails with `InvalidParameterException: A domain must be associated with this user pool.` error

### ISSUE THREAD

**Issue by sappusaketh** [amazon-connect/voicemail-for-amazon-connect#5]
I m following [this doc](https://s3.amazonaws.com/solutions-reference/voicemail-for-amazon-connect/latest/voicemail-for-amazon-connect.pdf) to configure voicemail for connect and I have given user pool domain prefix as `xy-dev` and it successfully creates `CopyLambdaArtifacts`, `VoiceMailStack` stacks but it fails in VoiceMailPortalStack creation with `InvalidParameterException: A domain must be associated with this user pool.` error during `customizeUserPool`. I tried deploying my stack in `us-west-2`. During rollback I am getting an error `The following resource(s) failed to delete: [UserPoolDomain].` and  `User pool us-west-2******* does not exist.` in `VoiceMailStack`

**Comment by sappusaketh** [comment]
It is because I used the old template please update template links in [this doc](https://s3.amazonaws.com/solutions-reference/voicemail-for-amazon-connect/latest/voicemail-for-amazon-connect.pdf) so that next one won't get lost and waste their time in figuring out what went wrong

**Comment by efh365** [comment]
Hi,

Thank you for making me aware of an outdated url. I will get that fixed. For the user pool domain, those are globally unique so the stack failed to create due to the domain not being unique. We are working on making this error more obvious.
