### ISSUE TITLE
Best Way to Delete Old Voicemails

### ISSUE THREAD

**Issue by chrispiccaro18** [amazon-connect/voicemail-for-amazon-connect#50]
Is there a recommended way to delete old voicemails? When testing the system out I deleted some manually in S3 but that triggered/broke the Lambda: ContactVoiceMailStream

**Comment by chrispiccaro18** [comment]
Following up on this. Any ideas?

**Comment by efh365** [comment]
Hi Chris, can you elaborate on how it triggered/broke the contact voicemail stream lambda function? I just deleted a voicemail from S3 and it did not trigger that function

**Comment by chrispiccaro18** [comment]
Looks like I can't replicate the issue I was thinking of. Maybe I was altering the DynamoDB table back when I originally messed things up. Regardless, is it safe to simply delete old voicemails in the S3 bucket?

**Comment by efh365** [comment]
Yes, deleting the object in S3 should be safe. It would only be a problem if someone tried to access the object through the presigned url and the object wasnt there.

**Comment by chrispiccaro18** [comment]
Great, thanks!
