### ISSUE TITLE
Handling a large number of users in Connect ( > 4800)

### ISSUE THREAD

**Issue by sdebrosse** [amazon-connect/voicemail-for-amazon-connect#51]
There are currently a few issues with handling Connect instances that have over 4800 users (approximately).

- The scan() function inside dynamo.js currently only returns a maximum of 1 MB of data from the Users table. This corresponds to about 4800 users stored. This can actually result in data loss: if certain users are not returned from DDB but do exist in Connect, the Sync Lambda function will treat them as new users and overwrite the existing records (and those user's stored extension will be cleared). Solution: the scan function should be modified to look for LastEvaluatedKey in the response and continue retrieving additional items if necessary.

- In connect.service.js, MaxResults is set to '100' . As a result, if there are a large number of users to retrieve from Connect (via ListUsers API), the Sync Lambda functions are very likely to hit rate limits. I'd recommend that MaxResults be increased to '1000'.

**Comment by efh365** [comment]
For other users with this issue, this bug has been fixed in the new development branch. Please refer to the PR linked above to see the changes or pull down the most recent code from the new branch. We will work on updating the AWS Solution with the fix.

**Comment by dfw100** [comment]
I am closing the issue as this bug has been fixed in the new development branch. Please feel free to open a new ticket if anything else comes up.
