### ISSUE TITLE
Save/Download button dimmed when trying to download the contact flows

### ISSUE THREAD

**Issue by jo9553** [amazon-connect/voicemail-for-amazon-connect#53]
Hi, 
What criteria to make the button enable for downloading??
Thanks,
Jo

**Comment by jo9553** [comment]
i have found it.

**Comment by MrMartinR** [comment]
I  had the same problem, 
Solution: Do not use the same email address for the Manager and the Admin, if you did, edit the stack and change it, I used the same and I was logged as Manager instead of Admin (You cannot download the file as Manager)
