### ISSUE TITLE
VoicemailStac-KvsProcessRecordingLambd not processing voicemail CTRs

### ISSUE THREAD

**Issue by mick-shaw** [amazon-connect/voicemail-for-amazon-connect#54]
I've deployed this package multiples times without issue.  Having issues this time.  This is fairly large Connect instances with +3500 users.  Extension lookup is working as expected.  However, voicemail CTRs are not being processed by the VoicemailStac-KvsProcessRecordingLambda.  Other CTRs are showing up, but I never see the CTRs associated with the voicemail flows.  The only deviation is that I'm hard-setting the Agent Extension rather than prompting and I'm using an existing CTR.

**Comment by mick-shaw** [comment]
Disregard.  Removing the kvs kinesis trigger and re-adding it resolved the issue

**Comment by mbulandra** [comment]
It seems I have the same issue - KvsProcessRecordingLambdaFunction is not processing CTRs, but in my case recreating the trigger did not solve the issue. I am using a Kinesis Data Stream that was configured previously for other purposes. I have modified the IAM role by adding the existing stream to the resources.

Did you change any settings when creating the trigger again?
