### ISSUE TITLE
Reg : Notification service code issue

### ISSUE THREAD

**Issue by kmuthuraja** [amazon-connect/voicemail-for-amazon-connect#55]
Hi,

When i enabled the sms only option, the current code not sending the sms notifications to the phone number. The source code have the below conditions, which doesn't support to trigger sms notifications for the send only sms condition.

    } else if (shouldSendSMS && agentSMSPhoneNumber) {
                console.log("Send ONLY SMS");
                return Promise.resolve();

The above code should be modified as below

  else if (shouldSendSMS && agentSMSPhoneNumber) {
                console.log("Send ONLY SMS");
                return this.getDeliveryContents(options, voicemail).then(contents => {
                    return this.sendTextMessage(voicemail, agentSMSPhoneNumber, contents);
                });

After added the above code, now the sms notifications works only for the sms condition.

Please do the needful.

**Comment by efh365** [comment]
Thanks for finding this bug. We pushed the fix to the development branch. We will update the main branch on the next solution update. 

https://github.com/amazon-connect/voicemail-for-amazon-connect/commit/a21da6bbc093725c8eef0ebed3f95e0a17d3a1a8
