### ISSUE TITLE
Voicemail admin portal incompatible with Cloudwatch ipv6

### ISSUE THREAD

**Issue by Vigrond** [amazon-connect/voicemail-for-amazon-connect#57]
I was having difficulty accessing Cloudwatch admin portal for voicemail ( access denied errors ).

After disabling ipv6 in Cloudwatch, these permission errors seem to have been resolved.

Guide should probably be updated.

**Comment by angelacyu** [comment]
Thanks for bringing this to our attention. Will add to guide for next iteration.

**Comment by khastation** [comment]
@Vigrond can you provide specific logs for your issue? we're not able to reproduce this in our environment.

**Comment by dfw100** [comment]
We are closing the issue since we haven't got logs from you to look in to the issue. Please reopen the issue if needed.
