### ISSUE TITLE
Error when sending transcribed voicemails: Missing SecretID from params

### ISSUE THREAD

**Issue by jaymaire** [amazon-connect/voicemail-for-amazon-connect#58]
Hi there,

We have been using the voicemail solution in production for 2 clients -- previously have had no issues thus far which is great.

However we have found that recently with one of our clients, the voicemail file (.wav) is still being sent, but the transcriptions have stopped coming through with the emails. No changes have been made to the system.

Upon investigating cloudwatch for the lambda function TranscriptionEventsLambda, we can see the below error -- Missing SecretID from params.

Any idea what this could be?

Cheers
Jaydon

![image](https://user-images.githubusercontent.com/38898109/126419564-fbe28a23-9541-46be-8321-18ce805c2eb6.png)

**Comment by dfw100** [comment]
Hi @jaymaire, Sorry for reverting late on this. Will it be possible for you to check the following - 
1. Secrets Manager has a secret called VoicemailSecret (It is created as part of Cloudformation deployment)
2. The Lambda function ContactVoicemailStreamLambdaFunction has an environment variable called SECRET_ARN and the value is set to the ARN of the above secret.

**Comment by kqia040** [comment]
Hey jaymaire, were you able to resolve this issue?

**Comment by khastation** [comment]
@jaymaire we've confirmed this bug and are tracking it internally. You can solve it by changing the **aws-connect-vm.template**, add a 'SECRET_ARN' envrionment variable to `TranscriptionEventsLambdaFunction` and then 
Add permissions to retrieve secret to the `TranscriptionEventsIamRole`.
We'll target a fix in the next release, but this shouldn't affect functionality of the solution.
