### ISSUE TITLE
No unit tests to run

### ISSUE THREAD

**Issue by sappusaketh** [amazon-connect/voicemail-for-amazon-connect#6]
In the repo read me it says `cd ./source/aws-connect-vm-serverless
npm run test` but there are no tests to run

**Comment by eugene00x** [comment]
I have the same problem:

$ npm run test

> aws-connect-vm-api@1.0.0 test /Users/elutsenko/Projects/AMZVoiceMail/source/aws-connect-vm-serverless
> jest tests/*.test.js

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0

**Comment by efh365** [comment]
Sorry for the delay here. Thank you for pointing this out! It looks like the test directory was not included when this was pushed to GitHub. I have some tests available locally. I will see why the tests werent pushed and add it in the next revision.

**Comment by efh365** [comment]
We have updated the solution to include the few unit tests we have (we plan to add more unit tests in the future)
