### ISSUE TITLE
Send Email to 2 Email address

### ISSUE THREAD

**Issue by manush-7** [amazon-connect/voicemail-for-amazon-connect#60]
I want to integrate 2 email addresses as delivery emails. I tried manipulating the lambda code "voice-mail\handler\voicemail.js" but I'm not able to get an exact solution to modify it. 

Also, how do I roll out new updates to code? Just zip it and upload to S3 or we need CodeBuild pipeline.

**Comment by angelacyu** [comment]
Hi, you would be able to test your code changes with a simple upload. No need for CodeBuild pipeline.

Please follow the instructions here https://github.com/amazon-connect/voicemail-for-amazon-connect/tree/master/source/aws-connect-vm-serverless to set up your development environment

**Comment by manush-7** [comment]
Hi, @angieyu thanks for the reply. 

Is there any timeline or change that I could implement in order to send emails to multiple recipients?
