### ISSUE TITLE
Missing Role Permissions - TranscriptionEventsLambd

### ISSUE THREAD

**Issue by shaifd** [amazon-connect/voicemail-for-amazon-connect#61]
Hello,
Our CloudWatch logs show there is a problem with the permissions set for the TranscriptionEventsLambd role.
The following details are from the CloudWatch logs. 

`"principalId": "***-TranscriptionEventsLambd-***",
"eventSource": "secretsmanager.amazonaws.com",
"eventName": "GetSecretValue",
"errorCode": "AccessDenied",
"errorMessage": "User: arn:aws:sts::***:assumed-role/***-TranscriptionEventsIamRo-***-TranscriptionEventsLambd-*** is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:eu-west-2:***:secret:VoicemailSecret-***"`

AWS support advised to create this issue here :)

Thanks!

**Comment by khastation** [comment]
@shaifd this issue is now fixed in the development branch with  github-development-release-dev_1.0.7
