### ISSUE TITLE
Direct call extension transfer (single phone number)

### ISSUE THREAD

**Issue by rogerfydp** [amazon-connect/voicemail-for-amazon-connect#62]
First, thank you for this amazing project and to everyone that made it possible!

I would like to expand the capabilities of the default project, and allow direct extension calls from client.

This was already pointed out in a different discussion that should be possible _Originally posted by @efh365 in https://github.com/amazon-connect/voicemail-for-amazon-connect/issues/34#issuecomment-696916573_

Being possible, I've already modified the default workflows, and they all work fine. Only thing I'm still not happy about is how to grab extension from direct call.

Approach:
If phone number is "PhoneNumber" and extension number is "ExtensionNumber" only way I get it to work is to dial "PhoneNumber,ExtensionNumber" separating phone and extension by a "," so it creates a pause until call is established and then "ExtensionNumber" is automatically provided and grabbed directly using a "Store customer input" block directly in the first contact flow. This works.

Note: Other approaches such as replacing previous "," by "#" or '*' don't seem to work. Only alternative ';' works like "," but with customer having to accept if to pass arguments or not (which is not what I want).

What does not convince me:
1) To be able to properly grab the extension, I must set the "Store customer input" to a "Timeout before first entry" of at least 2-3 seconds, if not, extension is not grabbed properly. This is not perfect, as if someone calls without extension (regular project workflow), a noticeable delay of this 2-3 seconds will occur until automated workflow asking extension number or other services starts.

2) Don't know if it’s a standard separating phone and extension with a ",". To me it makes sense, but don't know if we write down this format in a "personal contact card" is intuitive or not, as some phones, don't even display the "," when dialing the number and you need to know that you need to hold the "*" key to generate a ",".

I would like to know if there are better ways (or if I'm doing it already completely wrong) to accomplish direct call via extension without having to have a dedicated phone number per agent and then redirect them to agents. I'm just interested in a single phone number and taking advantage of this amazing project. 

Thanks!

**Comment by angelacyu** [comment]
Hi, how do you dial a number with "PhoneNumber,ExtensionNumber"? I don't have a "," on my phone keypad so trying to understand how you manage this.

**Comment by dfw100** [comment]
Closing the issue since there is no enough info to look in to it. Please reopen the ticket with answer to @angieyu question above.

**Comment by rogerfydp** [comment]
@dfw100, I don't see the point of closing this thread just because of @angieyu question. The answer to that, is already stated on the initial comment (Point 2), 

> as some phones, don't even display the "," when dialing the number and you need to know that **you need to hold the "*" key to generate a ","**.

Furthermore, any search engine, provides numerous results for Android, iPhone... users on how to handle and create "Pause" (,) or "Wait" (;). See [Link 1](https://www.wikihow.com/Call-an-Extension-Number), [Link 2](https://www.howtogeek.com/263546/how-to-dial-phone-extensions-automatically-with-your-iphone/), [Link 3](https://www.ubergizmo.com/how-to/automatically-dial-extensions-android/)

**Comment by angelacyu** [comment]
Seems like you did a great job making modifications on top of this open source project. I'm not aware of others who have tried to accomplish the same thing. Is there a particular question you have? @rogerfydp
