### ISSUE TITLE
Unable to get transcriptions if AWS account has opted out of using content for quality improvements

### ISSUE THREAD

**Issue by FarOutWest** [amazon-connect/voicemail-for-amazon-connect#63]
When trying to transcribe voicemails we are unable to process them since we have opted out of using our data for quality improvements. The API docs found here:  https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/transcribe/model/StartTranscriptionJobRequest.html 
and here:
https://docs.aws.amazon.com/transcribe/latest/dg/opt-out.html
say we can provide the API method with an OutputBucket. However, we are having trouble finding out how to do this. Or where to add it. A parameter for an output bucket for Transcribe would be super useful for our use case and I'm sure others who wish not to share data with AWS. 

Here is a snippet of the error message we see in lambda:
`"You must specify a value for outputBucketName because your account, #######, has opted out of using your content for quality improvements. Make sure you provide a value for outputBucketName and try your request again. (Service: AmazonTranscribe; Status Code: 400; Error Code: BadRequestException;`

If an update to the template is too difficult for your team. Perhaps some instructions on how to modify and deploy this solution would be helpful. I can't seem to find the necessary documentation for repackaging this repository for deployment.

**Comment by dfw100** [comment]
Hi FarOutWest, thanks for the feedback. We have added it to the backlog, but at this point it's hard to tell when we'll get to it. We will update our changelog if it is supported in future. In the meantime, if you are able to resolve this, we would encourage you to send a pull request.

Regarding your concern repackaging the solution, it is described [here](https://github.com/amazon-connect/voicemail-for-amazon-connect#building-distributable-for-customization) . Please try and let us know if you need further help.
