### ISSUE TITLE
multiple instances in one account, can share one voice mail service?

### ISSUE THREAD

**Issue by DrVoIP** [amazon-connect/voicemail-for-amazon-connect#65]
In an environment in which there are two or more call centers implemented in a single account, how to set this up so both  call centers can use the same voice mail infrastructure.  The formation template asks for instance ARN, is there a way to accomplish this or do you have to built the vm solution twice?

**Comment by dfw100** [comment]
Hi DrVoIP, the solution is designed to work per instance of Amazon Connect only. You need to deploy per instance. 
We will update our changelog if it is supported in the future. You can subscribe to GitHub repo notification emails for updates.
