### ISSUE TITLE
Remediate Log4js

### ISSUE THREAD

**Issue by fkhan439** [amazon-connect/voicemail-for-amazon-connect#71]
Can you let me know the steps to mitigate the existing Voicemail Solution

**Comment by ranep210** [comment]
Please help with resolution

**Comment by nhira** [comment]
Please note the most recent version bumps log4j dependencies:
https://github.com/amazon-connect/voicemail-for-amazon-connect/blob/master/CHANGELOG.md#104---2021-12-21

**Comment by khastation** [comment]
Closing since the log4j issue has been remediated with the latest release `1.0.4`
