### ISSUE TITLE
The "Send ONLY SMS" condition isn't implemented

### ISSUE THREAD

**Issue by tombray** [amazon-connect/voicemail-for-amazon-connect#76]
I configured an agent to only receive SMS voicemail notifications and it wasn't working. I dug into the source code and discovered that this case isn't handled in `notification.service.js`:

```
            } else if (shouldSendSMS && agentSMSPhoneNumber) {
                console.log("Send ONLY SMS");
                return Promise.resolve();
```

**Comment by khastation** [comment]
This is now fixed with `v1.1.0`
