### ISSUE TITLE
Resource handler returned message: "Unzipped size must be smaller than 262144000 bytes

### ISSUE THREAD

**Issue by gyl9196** [amazon-connect/voicemail-for-amazon-connect#77]
Hi,

I am trying to use the "development" branch to add voicemail feature to my instance. However, when use the cloudformation at the last step. It fails due to a function called "SolutionHelperFunction" is over 262144000 bytes. 

Is there any workaround or you need to fix that?

Resource handler returned message: "Unzipped size must be smaller than 262144000 bytes (Service: Lambda, Status Code: 400, Request ID: 69b4c29e-e336-421f-a6ec-ce7c413a93e7, Extended Request ID: null)" (RequestToken: 282abe5b-810f-a238-fe9e-2b4f209af5bb, HandlerErrorCode: InvalidRequest)

thanks very much

**Comment by khastation** [comment]
Please use the main branch since it is up to date, we will be deprecating the development branch shortly.
