### ISSUE TITLE
No agent sync

### ISSUE THREAD

**Issue by PartialAvocado** [amazon-connect/voicemail-for-amazon-connect#8]
Hi. Thanks for the very promising solution.

I've deployed the stack and have been able to log into the management portal. I've clicked Sync Agents, then Sync on the pop-up, and nothing happens -- no error message, nothing at all. Refresh reveals nothing.

I'm troubleshooting, but wonder if you have any ideas. Thanks.

**Comment by efh365** [comment]
Im sorry to hear that! Can you check the CloudWatch logs to see if there is an error? You should look for the Lambda function that has "SyncRequest" in the name

**Comment by DrVoIP** [comment]
i note that i had similar problems and found that when I added the Instance ID to the CF parameters,I put the entire ARN link in that parameter.  They just want last part of the IRN, the instance ID not the entire ARN string.

**Comment by PartialAvocado** [comment]
@DrVoIP I definitely pasted the whole ARN string (beginning with "arn") in the CF parameters, so your idea is probably relevant, thanks. By ID, you mean just the xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx part, not the whole path with the region name? Thanks again.

**Comment by PartialAvocado** [comment]
So yes, that was it, I needed to put in just the 32-character instance ID, not the whole ARN string.

For some reason, now, the Download button isn't available and I haven't be able to make it available yet.

![image](https://user-images.githubusercontent.com/63624467/79405944-12e74a80-7fd9-11ea-814c-f2f47318c11f.png)
