### ISSUE TITLE
log4j issue in lambda created for AWS deafult voicemail stack 

### ISSUE THREAD

**Issue by akshaysawant54** [amazon-connect/voicemail-for-amazon-connect#80]
XXXXXXXXXX:/aws/lambda/exlsunshinevmail-Voicemai-KvsProcessRecordingLambd-XXXXXXXX
@logStream	
df341a87fd884d9db2177bd75354daf0
@message	
log4j:ERROR Could not find value for key log4j.appender.CONSOLE
@timestamp	
1650496396012

**Comment by kocedavi** [comment]
Hello!

Can you provide a little more information about the error you are receiving? Do you know what is triggering it? If possible please provide some steps so we can replicate the error in our own environment and take a closer look.

Additionally, were there any modifications to the code that you made in your environment?

Thanks,
David

**Comment by akshaysawant54** [comment]
Hi

We have deployed voicemail stack which provided by AWS on their website.

https://docs.aws.amazon.com/solutions/latest/voicemail-for-amazon-connect/template.html

The template was deployed in January 2022 and working as expected. But we have set the cloudwatch alarm for any lambda error. 

since 2 weeks we are getting lambda error notification - log4j:ERROR Could not find value for key log4j.appender.CONSOLE

Cloudwatch query

fields @timestamp, @message
| sort @timestamp desc
| filter @message like "ERROR"
| limit 20

result

==============================================================================
@log | 509392056473:/aws/lambda/exlsunshinevmail-Voicemai-KvsProcessRecordingLambd-Ce3YYp2FdRUK
@logStream | 2022/04/27/[$LATEST]04862b7b6a4f486ebfd751d41c765680
@message | log4j:ERROR Could not find value for key log4j.appender.CONSOLE
@timestamp | 1651064657603

==============================================================================

@ingestionTime | 1651064666695
@log | 509392056473:/aws/lambda/exlsunshinevmail-Voicemai-KvsProcessRecordingLambd-Ce3YYp2FdRUK
@logStream | 2022/04/27/[$LATEST]04862b7b6a4f486ebfd751d41c765680
@message | log4j:ERROR Could not instantiate appender named "CONSOLE".
@timestamp | 1651064657603

==============================================================================

**Comment by kocedavi** [comment]
Thanks for the additional details!

It looks like this issue is tied to how the voicemail stack is using Log4j after the most recent update.  If the overall solution is still working as expected then I think you can safely ignore the error for now. I've taken note though and will make sure the bug is fixed the next time we update the voicemail solution.

**Comment by akshaysawant54** [comment]
Thanks for addressing this issue. Do we have any timelines for resolutions or new update release.
