### ISSUE TITLE
Recorded voicemail link only sent to SMS phone, email box is not getting the same voicemail link

### ISSUE THREAD

**Issue by jasonzhangvdr** [amazon-connect/voicemail-for-amazon-connect#81]
1. created amazon connect instance
2. deployed Voicemail package with above instance
3. sync users on portal from connect instance
4. Define both email/sms as delivery options
5. Defined and verified delivery email account in SES

tested the voicemail, only phone received SMS but mailbox is not able to receive voicemail transcript link

**Comment by khastation** [comment]
This is working as expected in the latest version `1.1.0`, please reopen if you continue facing issues.
![image](https://user-images.githubusercontent.com/40148037/187810291-3ef50c36-afde-43d7-8bce-ce595bf3fc9d.png)
