### ISSUE TITLE
S3:GetSingedURL action does not exist 

### ISSUE THREAD

**Issue by jasonzhangvdr** [amazon-connect/voicemail-for-amazon-connect#82]
Refer to issue we created before: Recorded voicemail link only sent to SMS phone, email box is not getting the same voicemail link #81
We found VoicemailIamPolicy error: S3:GetSingedURL action does not exist

How to fix that?

**Comment by khastation** [comment]
This is working as expected in the latest version `1.1.0`, please reopen if you continue facing issues.
![image](https://user-images.githubusercontent.com/40148037/187810291-3ef50c36-afde-43d7-8bce-ce595bf3fc9d.png)
