### ISSUE TITLE
Language Supported

### ISSUE THREAD

**Issue by mfsuen** [amazon-connect/voicemail-for-amazon-connect#83]
I added the attribute "languageCode" in the contact flow "VM-Greeting.json" with "ja-JP". But it does not work. However, when i use either "zh-CN or ko-KR". Both are ok. I suspect the transcribe service source-code got issue. Would you check the code is compatible with the language, ja-JP??  thanks

**Comment by khastation** [comment]
This is fixed with `v1.1.0`.
