### ISSUE TITLE
CloudFront endpoint redirects to S3 bucket causing Access Denied

### ISSUE THREAD

**Issue by kiwifellows** [amazon-connect/voicemail-for-amazon-connect#84]
The stack has deployed correctly using the instructions at https://docs.aws.amazon.com/solutions/latest/voicemail-for-amazon-connect/deployment.html
However when going to the CloudFront distro using https://... the browser tries to redirect to the S3 bucket's URL. I didn't have this issue 4 weeks ago when we deployed this in another account. 
I have checked the S3 policies and CloudFront origin and behaviours and they are fine including the Origin Access Identity. Can you check if this is a new bug that may be able to be reproduced?
![image](https://user-images.githubusercontent.com/14047279/176353916-652084b3-acd9-4696-b16d-bac5175b994a.png)

**Comment by kiwifellows** [comment]
OK, here is the answer to this problem and how to resolve it immediately and also resolve it long term. The quick fix is to change the origin for the S3 bucket in cloud front Origin so that it points to the region specific S3 bucket. This won't be a problem in Us-east-1, but only all other regions. So instead of the default s3 global dns endpoint (mybucket.s3.amazonaws.com) you can change it to use mybucket.s3.<region>.amazonaws.com.

The reason for this issue is that the DNS propagation for other region specific DNS entries is immediate, but the global "s3.amazonaws.com" takes some time. CloudFront and S3 don't pick up on this being available yet after deploying, but give it about 12-24 hours and it sorts itself out.

Long term the deployment code/templates needs to be updated to use the region specific DNS entry for the CloudFront origin. I might do a pull request if I get some time :)

**Comment by khastation** [comment]
This is fixed with v1.1.0.

**Comment by fulcrum29** [comment]
Hey,
I encountered this bug again
