### ISSUE TITLE
Password reset code not received

### ISSUE THREAD

**Issue by prdshukla** [amazon-connect/voicemail-for-amazon-connect#88]
I am not getting the reset code for my Admin \ Manager account to my email if I need to reset those passwords.
Is there a way I can change it directly if these are stored in S3 \ DynamoDB etc...

**Comment by virtualgill** [comment]
Hi there! The users are stored in [Amazon Cognito](https://aws.amazon.com/cognito/), you can go to the Amazon Cognito user pool (it should have the prefix you set in the Cloudformation template when deploying) and trigger a password reset for your user there.

**Comment by prdshukla** [comment]
Thanks for response. It worked!!!
