### ISSUE TITLE
aws-connect-vm-portal - ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by PeifferWM** [amazon-connect/voicemail-for-amazon-connect#89]
**ISSUE** 
- ERESOLVE unable to resolve dependency tree

**RECREATION STEPS**
1. Download ZIP of repo (v1.1.0)
2. Unzip the file to your location of choice (I unzipped it on my development VDI)
3. Navigate to the source\aws-connect-vm-portal folder
4. Install the NPM packages 

**OUTPUT**
```
C:\dev\cim-amazon-connect-voicemail\source\aws-connect-vm-portal>npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: aws-connect-vm-portal@0.1.0
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.12.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"18.1.0" from react-native@0.70.3
npm ERR! node_modules/react-native
npm ERR!   peer react-native@">=0.59" from @react-native-community/netinfo@5.9.10      
npm ERR!   node_modules/@react-native-community/netinfo
npm ERR!     peer @react-native-community/netinfo@"^5.5.0" from @aws-amplify/core@2.3.0
npm ERR!     node_modules/@aws-amplify/core
npm ERR!       peer @aws-amplify/core@"^2.0.0" from aws-amplify-react@3.1.9
npm ERR!       node_modules/aws-amplify-react
npm ERR!       3 more (@aws-amplify/analytics, @aws-amplify/api, @aws-amplify/auth)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**REQUEST**
- Please let me know how to resolve this issue without having to upgrade all of the NPM packages to their latest version.
- Point me at any documentation on how to get the UI installed, built, and running on my local machine.  Our corporate policies will not allow deployment of this app using the provided steps, so code must be built and deployed by using Azure DevOps build agent pipelines.
- Are their plans on the backlog to get this updated to use more recent packages?  Many of the packages referenced are **years** older than their newest revision.

**CLARIFICATION**
- Yes, I can use `--legacy-peer-deps` on my `npm i` command and it will try to install the packages, but because of security vulnerabilities in three packages (see addendum) the installation won't complete.  Once I get past that issue I'll update this issue.

**UI UPDATES**
- Our plan is to submit a PR to the development branch that allows for more global settings (making SMS optional) and changing the Admin UI to hide transcription and SMS options when they are disabled globally.

**ADDENDUM**
There are also three npm packages that have security vulnerabilities (`express 4.18.2`, `immer 9.0.6`, `aws-sdk 2.555.0`) causing the packages to be quarantined by our nexus package server, but I'll follow the guidelines in your security policy to report them.

**Comment by virtualgill** [comment]
Hi @PeifferWM 
Since you are wanting to deploy this locally (and then through a pipeline), can you confirm you are using the [development branch](https://github.com/amazon-connect/voicemail-for-amazon-connect/tree/development) and Node 14 (you can use [nvm](https://nodejs.org/en/download/package-manager/#nvm) to easily switch in your local system) as per the README?
Thanks!
Gillian

**Comment by PeifferWM** [comment]
Hello and thank you for your comment @virtualgill ,

I am using code version 1.1.0, which I believe is from the master branch as that is more stable (updated appx twice a year). 

I looked at the note about Node 15 being an issue and saw that the ticket was closed.  I forget that 'closed' doesn't mean 'resolved', so should have looked at the comments as the 'resolution' was to use Node 14.

I was on Node 16, so had to downgrade.  As my development machine is Windows and it is a pretty locked down corporate virtual machine, NVM4W is not a simple app to use.  Changing Node versions requires complete uninstall/reinstall, but I did that.

Unfortunately, security violations in referenced packages stopped me from installing the packages without doing two more things (**after** we whitelisted both `express@4.18.2` and `immer@6.0.1`).
1. Update aws-sdk in package.json to use 2.1234.0 (Had to be 2.814 or higher)
2. Add a npm-shrinkwrap.json file (yes, more modern way is package-lock.json) to force aws-amplify to use a aws-sdk@2.1234.0.
```
  {
    "dependencies": {
      "@aws-amplify/core": {
        "version": "^2.2.1",
        "from": "@aws-amplify/core@^2.2.1",
        "dependencies": {
          "aws-sdk": {
            "version": "2.1234.0",
            "from": "aws-sdk@~2.518.0"
          }
        }
      }
    }
  }
```

That got the packages to install successfully.  But it still won't build.  (Remember, I'm on Windows, so the provided `npm run build` command doesn't work.)  Instead I just `npx react-scripts build` and this is the results.

![image](https://user-images.githubusercontent.com/115723879/196735733-d074df5c-948a-441a-84ad-f55bf6bae0d0.png)

Any other suggestions on how to get this to build without completely deviating from the code provided in the repository?

Thad

**Comment by PeifferWM** [comment]
I'm withdrawing this question.  After upgrading TypeScript to 3.5.5 the build errors go away.  I still think that this code should install and build with no modifications when it is downloaded, but I'll open a support ticket directly within the AWS console about that and work with our Account Manager about that, just like I'm emailing Amazon directly about the NPM packages with critical security vulnerabilities.
