### ISSUE TITLE
Store API Key with AWS Secrets Manager

### ISSUE THREAD

**Issue by davidAus5048** [amazon-connect/voicemail-for-amazon-connect#90]
hello working group, its been determined by our in house security that the storing of the ApiGatewayApiKey in the stack output is suitable, and best for the Cloud Formation template to instead store the key within AWS Secrets Manager.

Hoping within the next revision of this build, AWS Secrets Manager for the api key can be adopted.

**Comment by virtualgill** [comment]
Thanks @davidAus5048, I'll add it to the team's backlog for the next major release for this project
