### ISSUE TITLE
CloudFormation Stack - Create_Failed on template URL issue

### ISSUE THREAD

**Issue by FunkyMonkeyCloud** [amazon-connect/voicemail-for-amazon-connect#92]
I'm receiving the following error message upon deployment of the stack template:

Logical ID: CopyLambdaArtifactsStack
Status: CREATE_FAILED
Status reason: TemplateURL must be a supported URL.

I've attempted to deploy across multiple different AWS regions and receive the same error message.

![image](https://user-images.githubusercontent.com/29452895/203233487-e594726e-4311-45d6-8eaf-e1ed9f5b92ca.png)

**Comment by virtualgill** [comment]
Hi Henry, there are two ways of deploying this. Either you can use the cloudformation template linked in the pdf instructions (https://s3.amazonaws.com/solutions-reference/voicemail-for-amazon-connect/latest/voicemail-for-amazon-connect.template) or you can use the one in the github repo. If you are using the one in the github repo it's important that you follow the steps in the README first to build and populate it with the right values. Can I check which method you are using?

**Comment by FunkyMonkeyCloud** [comment]
Hi @virtualgill , thank you for your response. You're correct - I had mistakenly used the incorrect template for the deployment.

When I used the pdf instruction version I was able to get the stack to deploy successfully.

Appreciate your response

**Comment by phisada** [comment]
Used the pdf linked template, yet still receive "The following resource(s) failed to create: [AudioRecordingsBucket]."  I looked at the code in the template and there's no mention of a AudioRecordingsBucket.  On an added note, I was not able to create the initial stack until I removed  AccessControl: "LogDeliveryWrite" from the  VoicemailAccessLogBucket portion.  I learned that there was some security update by AWS in April that made it problematic.  I'm a newbie when it comes to this, so not absolutely clear on the process. Thanks

**Comment by virtualgill** [comment]
Hi @phisada the master/dev branches have been updated with the S3 ACL changes, but if you want to use the pre-populated template, you can use updated files and instructions here: https://aws-contact-center-blog.s3.us-west-2.amazonaws.com/voicemail-s3-default-acl-issue/vmv1s3fix.zip (detailed at the top of the [README](https://github.com/amazon-connect/voicemail-for-amazon-connect))
You'll find the AudioRecordingsBucket is in aws-connect-vm.template
