### ISSUE TITLE
log4j:ERROR Could not instantiate class [com.amazonaws.services.lambda.runtime.log4j.LambdaAppender]

### ISSUE THREAD

**Issue by PeifferWM** [amazon-connect/voicemail-for-amazon-connect#93]
Hello,

Cloned the master branch (1.1.0) and built it with Maven with **no changes** to the code.
_I did have to add three entries to the POM file under dependencyManagement because the versions referenced had vulnerabilities and were blocked by our repository manager (Nexus)._

1. com.fasterxml.jackson.core -> 2.12.7.1
2. com.google.protobuf -> 3.19.6
3. ch.qos.reload4j -> 1.2.23

I then deployed the .jar file, setup contact flow, and initiated a call.  

CloudWatch logs are showing this error:
* `log4j:ERROR Could not instantiate class [com.amazonaws.services.lambda.runtime.log4j.LambdaAppender]`
Further down are these three errors
* `log4j:ERROR Could not instantiate appender named "LAMBDA"`
* `log4j:ERROR Could not find value for key log4j.appender.CONSOLE`
* `log4j:ERROR Could not instantiate appender named "CONSOLE"`

Stack trace has the error originating on line 39 of KVSProcessRecordingLambda.java
* `private static final Logger logger = LoggerFactory.getLogger(KVSProcessRecordingLambda.class);`

I'm not a Java developer, so am not sure if this is an issue because:
1. An earlier issue ( #80  ) reported on this site mentioned that issues with log4j.appender could be ignored.
2. The next entry in CloudWatch is from `AudioStreamService.java`, which implies that the code kept on going.

I'm reporting this issue anyway because 
* After the two logs from `AudioStreamService.java` the lambda ends with no further information provided.  
  * ![image](https://user-images.githubusercontent.com/115723879/207433934-887de37a-055a-4e08-b6c9-96bcd2c68a5e.png)
* The data is not saved in Dynamo nor is there an audio file in the configured S3 bucket.  
* I can only assume that the logger errors may be at play.

**Note**: My team does not use Java, so our goal is to make zero changes to the code.  We want to treat this lambda as COTS and be able to drop in new versions when they are released with no need to deal with merge conflicts.

Please help.
Thad

**Comment by PeifferWM** [comment]
When I replaced the log4j2.xml file with this the rest of the logging appears and I found the problem - missing IAM permissions.

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">
<log4j:configuration debug="true" xmlns:log4j='http://jakarta.apache.org/log4j/'>
    <appender name="console" class="org.apache.log4j.ConsoleAppender">
        <layout class="org.apache.log4j.PatternLayout">
            <param name="ConversionPattern" value="%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n" />
        </layout>
    </appender>
    <root>
        <level value="DEBUG" />
        <appender-ref ref="console" />
    </root>
</log4j:configuration>
```

I'm not sure what was wrong with the original file.  I still get the same errors as above, but execution errors show up as well.

**Comment by virtualgill** [comment]
Hi @PeifferWM - is the solution working for you now? We know the errors are frustrating, but moving to another version of the library caused clashes with other dependencies so the decision was made to remain on that version since the errors aren't blocking the functionality of the solution.
