### ISSUE TITLE
Dependencies update

### ISSUE THREAD

**Issue by Fran-Rg** [amazon-connect/voicemail-for-amazon-connect#94]
Please enable github dependabot on the repo: https://github.com/dependabot

Python: Require 2.7 https://github.com/amazon-connect/voicemail-for-amazon-connect/blob/development/Pipfile#L10
Javascript: Most package.json modules are out of date and locked on minor version update

**Comment by davelemons** [comment]
Enabled and no outstanding Dependabot PRs
