### ISSUE TITLE
Email Delivery Issue to Office 365 

### ISSUE THREAD

**Issue by semaha2022** [amazon-connect/voicemail-for-amazon-connect#95]
Hi,

     Email Delivery module works fine for Gmail accounts.

     It is not getting delivered for Business email hosted in Office 365.

     Could you guide us on this? Which Lambda function is used for sending out email?

Thanks,
Selva

**Comment by virtualgill** [comment]
Hi @semaha2022 the email is sent through SES in https://github.com/amazon-connect/voicemail-for-amazon-connect/blob/master/source/aws-connect-vm-serverless/src/service/notification.service.js
However, if sending emails is working for gmail but not O365, it's likely that your O365 is blocking them. Talk to your O365 admin about adding the SES endpoint to the allowlist, and checking any other settings that determine what emails are allowed through.

**Comment by virtualgill** [comment]
I'm closing this issue since it is mostly likely to be a O365 configuration. If that is ruled out, feel free to come back and add additional information. Thanks!
